# -*- coding: utf-8 -*-
"""01_phobert_multitask_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/inhlqunhphng/01-phobert-multitask-training.c8e1f40d-3571-4e46-bb70-a3582aea6e89.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T180112Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D052d1b0670d68a5de5043d10f96c980c1f74da34f435b0dbf684161baceae49f2cbf189d565aa429d034feaf8e5f2ee4e139b2afe962bcf0052ef6aa7d97364f9608be027364c8d40ec8c5b3b45fb6ef2c7abbae314cd3e2e17890e336768279c2c84a09645ee9169fe6e3664f09915512a98ab6ebc89739a8d51f7f1522fd997498ce58aa41aea7bd7ca95a526c106389b124a26e2d01d39ab3cbbb0c83e98f0b9b5694ccc8c02c0b623674218cd9ed0c7488d71778d869ecf81a45b69e48416008f876341fca82fb3f69e0e9e990e8973edb924b0c2ac4504365b485cbb1c45d7cadd6144a7f58fab2ebe15c3ca027806c86a81583f5efaa9593da4120cd07
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
inhlqunhphng_vaccinenlp_clean_data_path = kagglehub.dataset_download('inhlqunhphng/vaccinenlp-clean-data')

print('Data source import complete.')

"""# 💉 01. PhoBERT Multitask Training - VaccineNLP Phase 5
Notebook này được xây dựng nhằm huấn luyện một mô hình ngôn ngữ tiếng Việt dựa trên kiến trúc Transformer, cụ thể là PhoBERT, theo hướng học đa nhiệm (Multitask Learning) trên bộ dữ liệu VaccineNLP.

1.  Mục tiêu nghiên cứu: Mô hình được thiết kế để thực hiện đồng thời ba nhiệm vụ phân loại, bao gồm:
- Misinformation Detection: Xác định một văn bản có chứa thông tin sai lệch (misinformation) hay không.
    + Nhãn: Tin giả / Không tin giả
    + Ý nghĩa: Hỗ trợ phát hiện và hạn chế lan truyền thông tin sai lệch liên quan đến vaccine.
- Stance Classification: Xác định quan điểm của người viết đối với vaccine.
    + Nhãn: Ủng hộ / Phản đối / Trung lập
    + Ý nghĩa: Phân tích thái độ cộng đồng đối với các vấn đề y tế.
- Sentiment Analysis: Phân tích sắc thái cảm xúc của văn bản.
    + Nhãn: Tích cực / Tiêu cực / Trung lập
    + Ý nghĩa: Hiểu rõ cảm xúc và phản ứng của người dùng trên mạng xã hội.
2. Phương pháp tiếp cận
- Sử dụng mô hình PhoBERT pretrained để tận dụng khả năng hiểu ngữ nghĩa tiếng Việt.
- Áp dụng Multitask Learning để:
    + Chia sẻ biểu diễn (shared representation) giữa các nhiệm vụ
    + Cải thiện hiệu suất tổng thể so với huấn luyện từng task riêng lẻ
- Thiết kế các classification heads riêng biệt cho từng nhiệm vụ trên cùng một backbone.
3. Môi trường thực thi: Khuyến nghị sử dụng môi trường có GPU để tối ưu tốc độ huấn luyện:
- Cloud:
    + Kaggle (GPU miễn phí)
    + Google Colab (GPU/TPU)
- Local:
    + Máy có hỗ trợ CUDA (NVIDIA GPU)
    + RAM ≥ 8GB (khuyến nghị ≥ 16GB)
4. Ý nghĩa ứng dụng: Nghiên cứu này có thể được ứng dụng trong:
- Giám sát thông tin y tế trên mạng xã hội
- Hỗ trợ truyền thông sức khỏe cộng đồng
- Phân tích hành vi và nhận thức của người dùng về vaccine
"""

import os

DATA_PATH = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data"
os.chdir(DATA_PATH)

# Cài đặt các thư viện cần thiết để chạy các đoạn mã sau
!pip install -q transformers[torch] datasets evaluate accelerate mlflow pyvi scikit-learn matplotlib seaborn tqdm

"""# CELL 1: Setup Môi trường"""

# Commented out IPython magic to ensure Python compatibility.
# [CELL 1] Setup Môi trường
# %pip install -q transformers[torch] datasets evaluate accelerate mlflow pyvi scikit-learn matplotlib seaborn
print("✅ Cài đặt môi trường hoàn tất!")

"""# CELL 2: Import thư viện & Cấu hình"""

# [CELL 2] Imports & Cấu hình
# ==============================
# [CELL 2] Imports & Cấu hình
# ==============================
import os
import json
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from transformers import AutoModel, AutoTokenizer, AutoConfig, get_linear_schedule_with_warmup
from torch.optim import AdamW

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score

from pyvi import ViTokenizer
import mlflow
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import seaborn as sns


# ==============================
# ⚙️ CẤU HÌNH ĐƯỜNG DẪN (KAGGLE)
# ==============================
BASE_PATH = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data"

DATA_PATH = os.path.join(BASE_PATH, "04_silver_labels/train_set_final.jsonl")
BENCHMARK_SAVE_PATH = os.path.join(BASE_PATH, "03_processed/benchmark_test_set.jsonl")

# 👉 Chỗ lưu model PHẢI dùng working (ghi được)
MODEL_SAVE_DIR = "/kaggle/working/phobert-multitask-v1"


# ==============================
# ⚙️ DEVICE
# ==============================
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ==============================
# 📂 TẠO THƯ MỤC OUTPUT
# ==============================
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)


# ==============================
# 🔍 DEBUG PATH (RẤT QUAN TRỌNG)
# ==============================
print(f"🚀 Device: {DEVICE}")
print(f"📂 BASE_PATH: {BASE_PATH}")

print("\n📁 Files trong BASE_PATH:")
print(os.listdir(BASE_PATH))

print("\n📁 Files trong 04_silver_labels:")
print(os.listdir(os.path.join(BASE_PATH, "04_silver_labels")))

print("\n📁 Files trong 03_processed:")
print(os.listdir(os.path.join(BASE_PATH, "03_processed")))

print(f"\n📄 Data path: {DATA_PATH}")
print(f"📄 Benchmark path: {BENCHMARK_SAVE_PATH}")
print(f"💾 Model save dir: {MODEL_SAVE_DIR}")

# ==============================
# 🔍 Kiểm tra cấu trúc thư mục trên Kaggle
# ==============================

def list_files(startpath):
    print(f"🔍 Đang kiểm tra thư mục: {startpath}")

    if not os.path.exists(startpath):
        print(f"❌ Không tìm thấy thư mục: {startpath}")
        return

    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * level
        print(f'{indent}{os.path.basename(root)}/')

        subindent = ' ' * 4 * (level + 1)
        for f in files[:10]:  # tối đa 10 file mỗi folder
            print(f'{subindent}{f}')


# ==============================
# 📂 PATH KAGGLE (SỬA Ở ĐÂY)
# ==============================
BASE_PATH = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data"

# ==============================
# 🚀 RUN
# ==============================
list_files(BASE_PATH)

"""# CELL 3: Tải & Làm sạch dữ liệu"""

# [CELL 3] Load & Clean Data
import json
import pandas as pd
import os

def load_data(file_path):
    if not os.path.exists(file_path):
        print(f"⚠️ Không tìm thấy file: {file_path}")
        return pd.DataFrame()

    data = []

    with open(file_path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            try:
                item = json.loads(line)

                # Chỉ lấy dữ liệu đã annotate
                if item.get('status') in ['llm_annotated', 'gold_annotated']:

                    ids = item.get('standardized_ids', [0, 3, 1])

                    data.append({
                        "text": item.get('text_cleaned', item.get('text', '')),
                        "misinfo_id": ids[0] if len(ids) > 0 else 0,
                        "stance_id": ids[1] if len(ids) > 1 else 3,
                        "sentiment_id": ids[2] if len(ids) > 2 else 1
                    })

            except json.JSONDecodeError:
                print(f"⚠️ Lỗi JSON dòng {i}")
                continue

    return pd.DataFrame(data)


# ==============================
# LOAD DATA
# ==============================
train_df = load_data(DATA_PATH)
val_test_df = load_data(BENCHMARK_SAVE_PATH)


# ==============================
# CHECK DATA
# ==============================
if not train_df.empty:
    print(f"✅ Train: {len(train_df)} samples")

    if not val_test_df.empty:
        print(f"✅ Benchmark: {len(val_test_df)} samples")

    print("\n📊 Sample data:")
    print(train_df.head(2))

else:
    print("❌ Không load được data → kiểm tra lại path ở CELL 2")

"""# CELL 4: Word Segmentation (pyvi) & Tokenization"""

# [CELL 4] Word Segmentation (pyvi) & Tokenization
TOKENIZER_NAME = "quynhphuong1209/phobert-multitask"
tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_NAME)

def preprocess_text(text):
    # PhoBERT yêu cầu văn bản đã được tách từ (Word Segmented)
    return ViTokenizer.tokenize(text)

train_df['text_segmented'] = train_df['text'].apply(preprocess_text)
val_test_df['text_segmented'] = val_test_df['text'].apply(preprocess_text)

print("✅ Tiền xử lý hoàn tất!")

"""# CELL 5: Validation Setup & Benchmark Finalization"""

# [CELL 5] Validation Setup & Benchmark Finalization
from sklearn.model_selection import train_test_split

# Tách tập Val từ Train Set để giữ Benchmark Set sạch hoàn toàn cho khâu đánh giá cuối cùng
train_df, val_df = train_test_split(train_df, test_size=0.1, random_state=42, stratify=train_df['stance_id'])
test_df = val_test_df

print(f"📊 Số lượng: Train={len(train_df)}, Val={len(val_df)}, Test={len(test_df)}")
print(f"💾 Benchmark Test Set đang sử dụng: {BENCHMARK_SAVE_PATH}")

"""# CELL 6: Model Architecture (Multitask)"""

# [CELL 6] Model Architecture (Multitask)
class VaccineMultitaskModel(nn.Module):
    def __init__(self, model_name=TOKENIZER_NAME, n_misinfo=3, n_stance=4, n_sentiment=3):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        hidden = self.encoder.config.hidden_size
        self.dropout = nn.Dropout(0.1)

        self.head_misinfo = nn.Linear(hidden, n_misinfo)
        self.head_stance = nn.Linear(hidden, n_stance)
        self.head_sentiment = nn.Linear(hidden, n_sentiment)

    def forward(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        # Sử dụng pooler_output cho classification
        pooled = self.dropout(out.pooler_output)

        return {
            "misinfo": self.head_misinfo(pooled),
            "stance": self.head_stance(pooled),
            "sentiment": self.head_sentiment(pooled)
        }

# Loss function kết hợp class weights (Sửa lỗi ValueError)
from sklearn.utils.class_weight import compute_class_weight

def get_loss_fn(df, task_key, n_classes, device):
    # Lấy danh sách các class thực tế có trong dữ liệu
    present_classes = np.unique(df[task_key])
    weights_val = compute_class_weight('balanced', classes=present_classes, y=df[task_key])

    # Tạo full weights tensor với giá trị 1.0 cho class thiếu (nếu có)
    full_weights = torch.ones(n_classes).to(device)
    for idx, cls_id in enumerate(present_classes):
        if cls_id < n_classes:
            full_weights[int(cls_id)] = weights_val[idx]

    return nn.CrossEntropyLoss(weight=full_weights.to(torch.float32))

# Khởi tạo loss với mapping chính xác
loss_m = get_loss_fn(train_df, 'misinfo_id', 3, DEVICE)
loss_st = get_loss_fn(train_df, 'stance_id', 4, DEVICE)
loss_se = get_loss_fn(train_df, 'sentiment_id', 3, DEVICE)

print("✅ Khởi tạo kiến trúc và Loss hoàn tất (đã fix lỗi weights)!")

"""# CELL 7: Dataset & Training Loop"""

# [CELL 7] Dataset & Training Loop
class VaccineDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len=256):
        self.data = dataframe
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        row = self.data.iloc[index]
        encoding = self.tokenizer(
            row['text_segmented'],
            truncation=True, padding='max_length', max_length=self.max_len, return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'misinfo': torch.tensor(row['misinfo_id'], dtype=torch.long),
            'stance': torch.tensor(row['stance_id'], dtype=torch.long),
            'sentiment': torch.tensor(row['sentiment_id'], dtype=torch.long)
        }

# DataLoaders
train_loader = DataLoader(VaccineDataset(train_df, tokenizer), batch_size=16, shuffle=True)
val_loader = DataLoader(VaccineDataset(val_df, tokenizer), batch_size=16)

# Optimizer
model = VaccineMultitaskModel().to(DEVICE)
optimizer = AdamW(model.parameters(), lr=2e-5)

def train_epoch(model, loader, optimizer):
    model.train()
    losses = []
    for batch in tqdm(loader):
        optimizer.zero_grad()
        ids = batch['input_ids'].to(DEVICE)
        mask = batch['attention_mask'].to(DEVICE)

        logits = model(ids, mask)

        l1 = loss_m(logits['misinfo'], batch['misinfo'].to(DEVICE))
        l2 = loss_st(logits['stance'], batch['stance'].to(DEVICE))
        l3 = loss_se(logits['sentiment'], batch['sentiment'].to(DEVICE))

        total_loss = 0.5*l1 + 0.3*l2 + 0.2*l3
        total_loss.backward()
        optimizer.step()
        losses.append(total_loss.item())
    return np.mean(losses)

# Chạy training (5 epochs)
EPOCHS = 5
print(f"🏃 Bắt đầu huấn luyện trong {EPOCHS} epochs...")
for epoch in range(EPOCHS):
    avg_loss = train_epoch(model, train_loader, optimizer)
    print(f"🔥 Epoch {epoch+1}/{EPOCHS} Loss: {avg_loss:.4f}")

"""# CELL 8 Evaluation & Save"""

# [CELL 8] Evaluation & Save

def evaluate(model, loader):
    model.eval()
    all_preds = {'m': [], 'st': [], 'se': []}
    all_labels = {'m': [], 'st': [], 'se': []}

    with torch.no_grad():
        for batch in loader:
            ids = batch['input_ids'].to(DEVICE)
            mask = batch['attention_mask'].to(DEVICE)
            logits = model(ids, mask)

            all_preds['m'].extend(logits['misinfo'].argmax(dim=1).cpu().tolist())
            all_preds['st'].extend(logits['stance'].argmax(dim=1).cpu().tolist())
            all_preds['se'].extend(logits['sentiment'].argmax(dim=1).cpu().tolist())

            all_labels['m'].extend(batch['misinfo'].tolist())
            all_labels['st'].extend(batch['stance'].tolist())
            all_labels['se'].extend(batch['sentiment'].tolist())

    print("--- MISINFORMATION ---")
    print(classification_report(all_labels['m'], all_preds['m']))
    print("--- STANCE ---")
    print(classification_report(all_labels['st'], all_preds['st']))
    print("--- SENTIMENT ---")
    print(classification_report(all_labels['se'], all_preds['se']))

evaluate(model, val_loader)

# Save Model
torch.save(model.state_dict(), os.path.join(MODEL_SAVE_DIR, "pytorch_model.bin"))
print(f"💾 Mô hình đã được lưu tại: {MODEL_SAVE_DIR}")

"""## 📊 Báo cáo Giám sát Huấn luyện (Multitask Summary)"""

import pandas as pd
import matplotlib.pyplot as plt

def summary_report(model, val_loader):
    model.eval()
    results = []
    tasks = {'misinfo': 'Misinformation', 'stance': 'Stance', 'sentiment': 'Sentiment'}

    # Ở đây chúng ta tái sử dụng logic evaluate để lấy các chỉ số chính
    # Trong thực tế, bạn có thể lưu các giá trị này vào một dict trong quá trình chạy evaluate()

    print("=== TỔNG HỢP KẾT QUẢ HUẤN LUYỆN ===")
    print(f"Device: {DEVICE}")
    print(f"Base Model: {TOKENIZER_NAME}")
    print(f"Final Training Loss: {avg_loss:.4f}")
    print("\nChỉ số F1-Score (Macro Avg) dự kiến:")

    # Mock data dựa trên output Cell 8 để hiển thị dashboard nhanh
    summary_data = {
        'Task': ['Misinformation', 'Stance', 'Sentiment'],
        'Accuracy': [0.81, 0.55, 0.65],
        'Macro F1': [0.66, 0.54, 0.62]
    }

    df_summary = pd.DataFrame(summary_data)
    display(df_summary)

    # Vẽ đồ thị so sánh
    df_summary.set_index('Task')[['Accuracy', 'Macro F1']].plot(kind='bar', figsize=(10, 5))
    plt.title('Performance Comparison across Tasks')
    plt.ylabel('Score')
    plt.xticks(rotation=0)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

summary_report(model, val_loader)

"""### 🏁 Kết thúc

"""

# ==========================================
# [CELL TEST NÓNG] - V2: Kỷ Luật Thép (Taxonomy Enforced)
# ==========================================
import torch
import torch.nn.functional as F
from pyvi import ViTokenizer

stress_tests = [
    "tiêm vs xog con t sốt cmn li bì, bs bảo bìh thg nhg trên mạng đầy vụ tự kỷ ròi, đm bọnn chóp bu lùa gà vkl =)))",
    "T.j.ê.m v.xln là thuyết â/m m/ư/u của Bjn Gết để cấy chj.p 5G dkyển con ng nhé mấy con giời. Tỉnh mộng đi đừg nạp mạng cho Big Fama nưã 🛑",
    "mới bú con as cha zenca bầm dập văng cmn nết 🤡 nma thui ráng để lấy thẻ xanh đi đu idol Hàn Xẻng. done mũi 2 nhóe mn!",
    "Bácsĩơi,bénhàem tiêmmũi5trong1 bịsưng cụcđỏ hơn1tuần rồicó saokg ạ??? Emsợquá bôidầugió mà kgđỡ :(",
    "Ai ns chích ngừa êm ru hông sốt thì bốc phét nhé. T vật vã 2 ngày tưởng đi chầu ông bà vải cmnr. Nma ko chích thì h chăc đag bú bình oxy cmnr. 10 điểm ko có nhưng 👍"
]

# Barem taxonomy cho output
TAXONOMY = {
    'misinfo': {1: "Tin giả", 2: "Chính xác", 0: "Không liên quan"},
    'stance': {1: "Ủng hộ", 2: "Phản đối", 0: "Trung lập", 3: "Không rõ"},
    'sentiment': {2: "Tiêu cực", 0: "Trung tính", 1: "Tích cực"}
}

print("🚀 ĐANG KHỞI CHẠY HỆ THỐNG XAI (CHẾ ĐỘ KỶ LUẬT THÉP)...\n")

for i, text in enumerate(stress_tests):
    print(f"--- TEST CASE {i+1} ---")
    print(f"📥 Input: {text}")

    # Preprocess
    segmented_text = ViTokenizer.tokenize(text)
    inputs = tokenizer(segmented_text, return_tensors="pt", truncation=True, padding=True, max_length=256).to(DEVICE)

    model.eval()
    with torch.no_grad():
        logits = model(inputs['input_ids'], inputs['attention_mask'])

        # Trích xuất xác suất (Probability Extraction)
        p_m = F.softmax(logits['misinfo'], dim=1)[0]
        p_st = F.softmax(logits['stance'], dim=1)[0]
        p_se = F.softmax(logits['sentiment'], dim=1)[0]

    # Logic Lý luận dựa trên xác suất
    m_idx = p_m.argmax().item()
    st_idx = p_st.argmax().item()
    se_idx = p_se.argmax().item()

    conf_m = p_m[m_idx].item()
    conf_st = p_st[st_idx].item()
    conf_se = p_se[se_idx].item()

    reasoning = f"Mô hình nhận diện dựa trén trọng số hội tụ: Misinfo ({conf_m*100:.1f}%), Stance ({conf_st*100:.1f}%), Sentiment ({conf_se*100:.1f}%). "
    reasoning += "Độ chuẩn: " + ("CAO" if conf_m > 0.7 else "TRUNG BÌNH/THẤP (CầN CHECK LẠI)")

    print("🧠 Model Reasoning:")
    print(f"Lý luận: {reasoning}")

    # Kết quả theo format taxonomy
    res_m = TAXONOMY['misinfo'].get(m_idx, "N/A")
    res_st = TAXONOMY['stance'].get(st_idx, "N/A")
    res_se = TAXONOMY['sentiment'].get(se_idx, "N/A")

    print(f"Kết quả: [{res_m}] | [{res_st}] | [{res_se}]")
    print("\n" + "="*70 + "\n")