# -*- coding: utf-8 -*-
"""02_gemma4_4b_qlora_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/inhlqunhphng/02-gemma4-4b-qlora-training.1bb44963-4512-47c3-86f5-58fe3fbc6ec8.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T181925Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6fcb098610d85b2172ed468245efc0663adaa9fd0422f15daf9cfa0b0304e359140be96f0a6f2e10f3b032c97c8f451146d47bb57fda377a62566a9bc31e1e1e89d2d565a9ee0c855927f30b2b9cb1bec6788283e6baf43a0f3935d317acaab9e00ace46d93239e43340696796b91f98ec7acd9b54a4abdf7d05588c79729b905f976756b5b5bc42988bd97c895c457897a8ce52d4c6a92b1d6020c463e16faad53af01b229aacca9189f463f6aca3c9dc1f51eb90e226527709022f52f200c332cb39b3a299b39eb761ba4bf169e8d0c7aa0495442c27830d27e6c37f01e3871a2e198d1e890fc3927e6326f8cc86974be6bc868f1320093cc44ad6395a57ca
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
inhlqunhphng_vaccinenlp_clean_data_path = kagglehub.dataset_download('inhlqunhphng/vaccinenlp-clean-data')

print('Data source import complete.')

# Cài Unsloth cho Kaggle (tag "kaggle-new" đúng cho môi trường Kaggle)
!pip install "unsloth[kaggle-new]" --upgrade --quiet

print("✅ Cài đặt hoàn tất! Vào Menu > Run > Restart Session, rồi chạy từ Cell 2.")

# import IPython
# IPython.Application.instance().kernel.do_shutdown(True)

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import torch
from huggingface_hub import login
from datasets import load_dataset
from unsloth import FastModel
from unsloth.chat_templates import get_chat_template, train_on_responses_only
from trl import SFTTrainer, SFTConfig

from kaggle_secrets import UserSecretsClient
try:
    user_secrets = UserSecretsClient()
    VaccineNLP_TOKEN = user_secrets.get_secret("VaccineNLP")
    login(token=VaccineNLP_TOKEN)
    print("✅ Đăng nhập HuggingFace thành công!")
except Exception as e:
    print(f"⚠️ Không tìm thấy VaccineNLP: {e}")

# FastModel (không phải FastLanguageModel) — đúng cho Gemma 4 multimodal
model, tokenizer = FastModel.from_pretrained(
    model_name = "unsloth/gemma-4-E4B-it",  # Tên đúng trên HuggingFace
    max_seq_length = 1024,
    dtype = None,           # Unsloth tự detect BF16/FP16
    load_in_4bit = True,
)

# LoRA — chỉ tune language layers, bỏ qua vision/audio tower
model = FastModel.get_peft_model(
    model,
    finetune_vision_layers   = False,  # Task text-only, không cần vision
    finetune_language_layers = True,
    finetune_attention_modules = True,
    finetune_mlp_modules     = True,
    r = 16,
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",  # Unsloth chống OOM tốt hơn HF
    random_state = 3407,
)
model.print_trainable_parameters()
print("✅ Load model hoàn tất!")

TRAIN_PATH      = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data/05_model_ready/train_v2_seg.jsonl"
TEST_PATH       = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data/03_processed/benchmark_test_set.jsonl"
MODELS_SAVE_DIR = "/kaggle/working/gemma_qlora_xai"
os.makedirs(MODELS_SAVE_DIR, exist_ok=True)

for path in [TRAIN_PATH, TEST_PATH]:
    print(("✅" if os.path.exists(path) else "❌ KHÔNG TÌM THẤY") + f": {path}")

# Dùng "gemma-4" (không phải "gemma-4-thinking") vì:
# Task classification không cần thinking tokens → tiết kiệm VRAM
tokenizer = get_chat_template(tokenizer, chat_template="gemma-4")

misinfo_map   = {0: "Không liên quan", 1: "Tin giả", 2: "Chính xác"}
stance_map    = {0: "Ủng hộ", 1: "Phản đối", 2: "Trung lập"}
sentiment_map = {0: "Tiêu cực", 1: "Trung tính", 2: "Tích cực"}

def format_prompt(row):
    text = row.get('text_cleaned') or row.get('text') or str(list(row.values())[0])
    reasoning = row.get('llm_reasoning', 'Phân tích dựa trên ngữ cảnh.')
    ids = row.get('standardized_ids') or [0, 3, 1]

    convo = [
        {"role": "user", "content": (
            f"You are an Explainable AI in Public Health. Analyze the text, "
            f"provide your reasoning first, then the structured labels.\n\nVăn bản: {text}"
        )},
        {"role": "model", "content": (
            f"Lý luận: {reasoning}\n"
            f"Kết quả: {misinfo_map.get(ids[0], 'Không liên quan')} | "
            f"{stance_map.get(ids[1], 'Không rõ')} | "
            f"{sentiment_map.get(ids[2], 'Trung tính')}"
        )}
    ]
    # removeprefix('<bos>') theo hướng dẫn Unsloth — Processor sẽ tự thêm lại khi train
    return {"text": tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False).removeprefix('<bos>')}

print("Đang tải và chia tập dữ liệu (90/10)...")
# Load raw dataset first to split
raw_train_ds = load_dataset("json", data_files=TRAIN_PATH, split="train")
split_ds = raw_train_ds.train_test_split(test_size=0.1, seed=42)

train_ds = split_ds["train"].map(format_prompt)
eval_ds  = split_ds["test"].map(format_prompt)
test_ds  = load_dataset("json", data_files=TEST_PATH, split="train").map(format_prompt)

print(f"✅ Train: {len(train_ds)} mẫu | Val: {len(eval_ds)} mẫu | Test: {len(test_ds)} mẫu")
print(train_ds[0]['text'][:300] + "...")

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = train_ds,
    eval_dataset = eval_ds,     # Tắt eval để tránh OOM trên T4
    args = SFTConfig(
        output_dir = MODELS_SAVE_DIR,
        dataset_text_field = "text",
        max_length = 1024,
        per_device_train_batch_size = 2,   # Unsloth cho phép batch=2 thay vì 1
        per_device_eval_batch_size = 1, # THÊM DÒNG NÀY
        eval_accumulation_steps = 1,    # THÊM DÒNG NÀY
        gradient_accumulation_steps = 4,
        warmup_steps = 10,
        num_train_epochs = 2,
        learning_rate = 2e-4,
        logging_steps = 10,
        save_strategy = "epoch",
        eval_strategy = "steps",
        eval_steps = 50,
        optim = "adamw_8bit",
        bf16 = torch.cuda.is_bf16_supported(),
        fp16 = not torch.cuda.is_bf16_supported(),
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none",
    ),
)

# Chỉ tính loss trên phần model trả lời, không tính loss trên câu hỏi
# → Tăng chất lượng fine-tuning đáng kể
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<|turn>user\n",
    response_part    = "<|turn>model\n",
)

print("🚀 Bắt đầu huấn luyện...")
trainer.train()

model.save_pretrained(f"{MODELS_SAVE_DIR}/final_model")
tokenizer.save_pretrained(f"{MODELS_SAVE_DIR}/final_model")
print(f"💾 Đã lưu model tại: {MODELS_SAVE_DIR}/final_model")

import shutil
from IPython.display import FileLink

print("Đang nén mô hình...")
# Nén thư mục final_model thành file gemma_unsloth_model.zip
shutil.make_archive('gemma_unsloth_model', 'zip', '/kaggle/working/gemma_qlora_xai/final_model')
print("✅ Hoàn tất! Bấm vào link bên dưới để tải về:")

# Hiển thị link tải
display(FileLink('gemma_unsloth_model.zip'))

from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()
VaccineNLP_TOKEN = user_secrets.get_secret("VaccineNLP")

repo_id = "quynhphuong1209/gemma-4-E4B-unsloth-vaccine-xai"

print(f"📤 Đang đẩy lên {repo_id}...")
model.push_to_hub(repo_id, token=VaccineNLP_TOKEN)
tokenizer.push_to_hub(repo_id, token=VaccineNLP_TOKEN)
print(f"🎉 Hoàn tất! https://huggingface.co/{repo_id}")

# ==========================================
# [CELL TEST NÓNG] - V2: Kỷ Luật Thép (Taxonomy Enforced)
# ==========================================
from transformers import TextStreamer
import torch

stress_tests = [
    "tiêm vs xog con t sốt cmn li bì, bs bảo bìh thg nhg trên mạng đầy vụ tự kỷ ròi, đm bọnn chóp bu lùa gà vkl =)))",
    "T.j.ê.m v.xln là thuyết â/m m/ư/u của Bjn Gết để cấy chj.p 5G dkyển con ng nhé mấy con giời. Tỉnh mộng đi đừg nạp mạng cho Big Fama nưã 🛑",
    "mới bú con as cha zenca bầm dập văng cmn nết 🤡 nma thui ráng để lấy thẻ xanh đi đu idol Hàn Xẻng. done mũi 2 nhóe mn!",
    "Bácsĩơi,bénhàem tiêmmũi5trong1 bịsưng cụcđỏ hơn1tuần rồicó saokg ạ??? Emsợquá bôidầugió mà kgđỡ :(",
    "Ai ns chích ngừa êm ru hông sốt thì bốc phét nhé. T vật vã 2 ngày tưởng đi chầu ông bà vải cmnr. Nma ko chích thì h chăc đag bú bình oxy cmnr. 10 điểm ko có nhưng 👍"
]

model.config.use_cache = True

print("🚀 ĐANG KHỞI CHẠY HỆ THỐNG XAI (CHẾ ĐỘ KỶ LUẬT THÉP)...\n")

for i, text in enumerate(stress_tests):
    print(f"--- TEST CASE {i+1} ---")
    print(f"📥 Input: {text}")

    # 1. IN-CONTEXT TAXONOMY PROMPT: Nhắc lại barem chấm điểm
    user_prompt = (
        f"Phân tích y tế: {text}\n\n"
        "Nhiệm vụ: Trình bày chuỗi lý luận (Chain-of-Thought) ngắn gọn và gán nhãn theo đúng 3 trục sau:\n"
        "1. Misinformation: Tin giả | Chính xác | Không liên quan\n"
        "2. Stance: Ủng hộ | Phản đối | Trung lập | Không rõ\n"
        "3. Sentiment: Tiêu cực | Trung tính | Tích cực\n\n"
        "Bắt buộc trả về đúng định dạng:\nLý luận: [Nội dung]\nKết quả: [Misinfo] | [Stance] | [Sentiment]"
    )

    messages = [
        {"role": "user", "content": [{"type": "text", "text": user_prompt}]}
    ]

    # Render prompt
    prompt_str = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    # 2. FORCED PREFILLING
    forced_prompt = prompt_str + "Lý luận: "
    inputs = tokenizer(text=forced_prompt, return_tensors="pt").to("cuda")

    print("🧠 Model Reasoning:")
    print("Lý luận: ", end="")

    from transformers import TextStreamer
    text_streamer = TextStreamer(tokenizer, skip_prompt=True)

    _ = model.generate(
        **inputs,
        streamer = text_streamer,
        # NHỮNG THAY ĐỔI CỐT LÕI NẰM Ở ĐÂY:
        max_new_tokens = 512,        # 1. THẢ XÍCH: Tăng từ 200 lên 512 tokens để nó có đủ hơi nói hết câu.
        temperature = 0.2,           # 2. Nhiệt độ: 0.2 đủ thấp để giữ logic, đủ cao để không bị kẹt lặp từ.
        repetition_penalty = 1.15,   # 3. Phạt lặp từ: Tăng lên một chút để ép nó nhanh chóng chốt "Kết quả" thay vì kể lể mãi.
        pad_token_id = tokenizer.eos_token_id, # Đảm bảo mô hình biết lúc nào nên tự động dừng (Stop generation).
        use_cache = True
    )
    print("\n" + "="*70 + "\n")