# -*- coding: utf-8 -*-
"""03b vaccinenlp gemma 4 inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/inhlqunhphng/03b-vaccinenlp-gemma-4-inference.3a544899-5f5f-4678-9dd5-cbbc874fdd5b.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260521/auto/storage/goog4_request%26X-Goog-Date%3D20260521T181813Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D15f06c0295b78ffaedb67964249f46dcb14d60a6f02558344989db35082b3649eac35873aa85e171789b85d5087203e7f0f9821109ed0ee6a3abba177018b980ae4f8ba42a4211663bf16a2ac30d043572f0ae032f6cb2d2630c8da40c720e385d34b1c3383edc0c6de18b4679f1c0ec5ed896ff531d017447898122039ca822e50a02f763a3937d107311af89e4b12e1092e9119078605bf7ca7cf07778902df769abc5820f2dacf13da6c953c12281c463129ccced0082aa5e6abfd3480a9dec6e801ffacfa23604625c1d7b97ac0d336eb209fe7d90cec9a62b63d53a4b4740cfe6787afc73b3760ee87b3612fbf4633ed0037e35be8e368a3d1d19e2b9f8
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
inhlqunhphng_vaccinenlp_clean_data_path = kagglehub.dataset_download('inhlqunhphng/vaccinenlp-clean-data')

print('Data source import complete.')

"""# 💉 Gemma-4 — NOTEBOOK B: INFERENCE & EVALUATION (Phase B)

**Phần 2/2 của pipeline** · Load model từ HF Hub · Taxonomy v3 · HUPH 2026

---

## 🔗 LIÊN THÔNG

Notebook này **pull model từ HF Hub** (do Notebook A push lên):
`quynhphuong1209/gemma-4-E4B-unsloth-vaccine-xai`

### Điều kiện tiên quyết
- Notebook A đã chạy xong (model đã push lên HF Hub) ✅
- Hoặc dùng model đã có sẵn trên HF (nếu chỉ tinh chỉnh inference)

### Output
- `gemma_inference_results_v3.jsonl` — dự đoán 186 mẫu Gold Test
- `gemma_v3_results.json` — schema chuẩn cho notebook benchmark report

⏱️ Ước tính: ~1-1.5h (batch inference + GEN tokens thích nghi)

> 💡 Notebook này chạy độc lập, KHÔNG train. Mỗi lần thử parser/prompt
> mới chỉ tốn ~1h, không tốn 2h train lại.

"""

# [CELL 1] Cài đặt Unsloth — bản vá: hiện lỗi thật + DỪNG nếu fail
import subprocess, sys, importlib

def pip_install(args, desc):
    """Chạy pip, IN TOÀN BỘ output (không giấu lỗi). Trả về returncode."""
    print(f"🏃 {desc}")
    print(f"   $ pip install {' '.join(args)}")
    proc = subprocess.run(
        [sys.executable, "-m", "pip", "install", *args],
        capture_output=True, text=True
    )
    if proc.returncode != 0:
        print("   ❌ STDOUT:", proc.stdout[-1500:])
        print("   ❌ STDERR:", proc.stderr[-1500:])
    else:
        print("   ✅ OK")
    return proc.returncode

print("📦 Bước 1/2 — Cài Unsloth (thử git mới nhất, fallback pip ổn định)")

# Thử 1: bản git mới nhất (fix Gemma-4). Nếu fail → thử bản pip ổn định.
rc = pip_install(
    ['--upgrade', '--no-cache-dir',
     'unsloth[kaggle-new] @ git+https://github.com/unslothai/unsloth.git'],
    "Thử bản git mới nhất"
)
if rc != 0:
    print("\n⚠️  Bản git fail → fallback bản pip ổn định")
    rc = pip_install(['--upgrade', '--no-cache-dir', 'unsloth'],
                     "Fallback: unsloth ổn định từ PyPI")
if rc != 0:
    print("\n⚠️  Vẫn fail → thử cài thủ công deps + unsloth --no-deps")
    pip_install(['--no-cache-dir',
                 'bitsandbytes', 'accelerate', 'peft', 'trl',
                 'triton', 'xformers', 'unsloth_zoo'],
                "Cài deps thủ công")
    rc = pip_install(['--no-cache-dir', '--no-deps', 'unsloth'],
                     "Cài unsloth --no-deps")

print("\n📦 Bước 2/2 — Xác minh import")

# Numpy check (Unsloth cần numpy>=2.0; Kaggle có sẵn 2.0.2)
try:
    import numpy as np
    print(f"   ✅ Numpy: {np.__version__}")
except Exception as e:
    print(f"   ⚠️  Numpy: {e}")

# GPU check
subprocess.run("nvidia-smi -L", shell=True)

# CRITICAL: import phải thành công, NẾU KHÔNG → raise để DỪNG notebook ngay
# (tránh chạy tiếp tới Cell 2 rồi crash khó hiểu)
try:
    importlib.invalidate_caches()
    from unsloth import FastModel  # noqa: F401
    print("   ✅ Unsloth FastModel import OK — sẵn sàng")
except Exception as e:
    raise RuntimeError(
        f"❌ CÀI UNSLOTH THẤT BẠI: {e}\n"
        "→ Xem STDERR phía trên để biết nguyên nhân.\n"
        "→ Kiểm tra: Kaggle Settings > Internet phải BẬT (ON).\n"
        "→ Kiểm tra: Accelerator phải là GPU (T4/P100), không phải None/CPU."
    )

# [CELL 2] Imports & GPU diagnostics
import os, gc, json, glob, datetime, shutil
import torch
from huggingface_hub import login, HfApi
from datasets import load_dataset

# Unsloth — nếu lỗi ở đây nghĩa là Cell 1 chưa chạy hoặc cài fail
try:
    from unsloth import FastModel
    from unsloth.chat_templates import get_chat_template, train_on_responses_only
except ModuleNotFoundError as e:
    raise RuntimeError(
        f"❌ {e}\n"
        "→ Cell 1 (cài Unsloth) CHƯA chạy hoặc đã FAIL.\n"
        "→ Chạy lại Cell 1 và đọc kỹ output. Internet phải BẬT."
    )

from trl import SFTTrainer, SFTConfig
from IPython.display import FileLink, display

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

if torch.cuda.is_available():
    props = torch.cuda.get_device_properties(0)
    total_gb = props.total_memory / 1e9
    print(f"🖥️  GPU: {props.name}")
    print(f"💾 VRAM: {total_gb:.1f} GB")
    print(f"🔢 CUDA: {torch.version.cuda}")
    print(f"⚡ BF16: {'✅' if torch.cuda.is_bf16_supported() else '❌ (dùng FP16)'}")
    if total_gb < 14:
        print("⚠️  CẢNH BÁO: VRAM < 14GB — có thể OOM khi train")
else:
    raise RuntimeError("❌ Không tìm thấy GPU — bật GPU T4 trong Kaggle Settings")

print("✅ Imports OK")

"""### Bước 1: Cấu hình Inference + Liên thông HF Hub"""

# [B-CELL 1] Config Inference — Taxonomy v3 + GEN tokens THÍCH NGHI
import os, glob, json, torch

# 🔗 LIÊN THÔNG: pull model từ HF Hub (Notebook A đã push)
HF_REPO_ID    = "quynhphuong1209/gemma-4-E4B-unsloth-vaccine-xai"
BASE_MODEL    = "unsloth/gemma-4-E4B-it"

def _find(patterns, fallback):
    for p in patterns:
        h = glob.glob(p, recursive=True)
        if h: return h[0]
    return fallback

TEST_PATH = _find(
    ["/kaggle/input/**/benchmark_test_set_v3.jsonl",
     "/kaggle/input/**/benchmark_test_set.jsonl"],
    "/kaggle/input/vaccinenlp-clean-data/03_processed/benchmark_test_set_v3.jsonl")

INFERENCE_OUT = "/kaggle/working/gemma_inference_results_v3.jsonl"
RESULTS_JSON  = "/kaggle/working/gemma_v3_results.json"
MAX_SEQ_LEN   = 1280
LOAD_IN_4BIT  = True

# ── GEN TOKENS THÍCH NGHI (theo yêu cầu) ──────────────────────────────────
# Trần 768 token NHƯNG StoppingCriteria cắt NGAY khi sinh đủ 3 nhãn:
#   - câu ngắn  → dừng ~200 tok (nhanh)
#   - câu cần suy luận dài → được phép tới 768 tok (đủ chỗ)
# Tự thích nghi, không phí thời gian — tốt hơn con số cố định 512.
GEN_MAX_NEW_TOKENS = 1024      # TRẦN: mean thực 509, cần thêm cho reasoning dài hoàn thành
GEN_MIN_NEW_TOKENS = 40        # sàn: tránh dừng quá sớm trước khi có nhãn
BATCH_SIZE_INF     = 4

# ── Label Maps — Taxonomy v3 CANONICAL ───────────────────────────────────
MISINFO_MAP   = {0: 'Tin gia',   1: 'Chinh xac'}
STANCE_MAP    = {0: 'Ung ho',    1: 'Phan doi',  2: 'Trung lap'}
SENTIMENT_MAP = {0: 'Tieu cuc',  1: 'Trung tinh', 2: 'Tich cuc'}
HC_MISINFO    = {0: 'Tin giả',   1: 'Chính xác'}
HC_STANCE     = {0: 'Ủng hộ',    1: 'Phản đối',  2: 'Trung lập'}
HC_SENTIMENT  = {0: 'Tiêu cực',  1: 'Trung tính', 2: 'Tích cực'}
N_CLASSES     = {'misinfo': 2, 'stance': 3, 'sentiment': 3}

print("✅ Config Inference v3 loaded")
print(f"   HF model : {HF_REPO_ID}")
print(f"   Test     : {TEST_PATH}")
print(f"   GEN tokens: thích nghi (sàn={GEN_MIN_NEW_TOKENS}, "
      f"trần={GEN_MAX_NEW_TOKENS}, dừng sớm khi đủ 3 nhãn)")
print(f"   Batch    : {BATCH_SIZE_INF}")

"""### Bước 2: 🔗 Load Model từ HF Hub (do Notebook A push)"""

# [B-CELL 2] Load Gemma-4 + LoRA adapter TỪ HF HUB (liên thông Notebook A)
from unsloth import FastModel
from unsloth.chat_templates import get_chat_template

print(f"📥 Pull model từ HF Hub: {HF_REPO_ID}")
print("   (model này do Notebook A train & push)")

# Thử load adapter từ HF Hub; fallback về local nếu cùng session với A
_local = "/kaggle/working/gemma_qlora_xai/final_model"
_model_src = _local if os.path.exists(_local) else HF_REPO_ID
print(f"   Nguồn: {_model_src}")

model, tokenizer = FastModel.from_pretrained(
    model_name     = _model_src,
    max_seq_length = MAX_SEQ_LEN,
    dtype          = None,
    load_in_4bit   = LOAD_IN_4BIT,
)
FastModel.for_inference(model)
tokenizer = get_chat_template(tokenizer, chat_template="gemma-4")

_txt_tok = getattr(tokenizer, "tokenizer", tokenizer)
if _txt_tok.pad_token_id is None:
    _txt_tok.pad_token    = _txt_tok.eos_token
    _txt_tok.pad_token_id = _txt_tok.eos_token_id
PAD_ID = _txt_tok.pad_token_id
model.config.pad_token_id = PAD_ID

assert model is not None, "❌ Model load thất bại"
print(f"✅ Model loaded từ: {_model_src}")
print(f"   processor = {type(tokenizer).__name__} | pad_id = {PAD_ID}")
print(f"   VRAM: {torch.cuda.memory_allocated()/1e9:.2f} GB")

"""### Bước 3: Prompt Builder & Output Parser (strict)"""

# [CELL 10] Parser ANSWER-FIRST v3 — FIX false-positive "(Tin gia)" tiêu đề task

REV_MISINFO_ORDER = [
    ('khong tin gia',1),('không tin giả',1),('khong sai',1),('không sai',1),
    ('dung su that',1),('đúng sự thật',1),('chinh xac',1),('chính xác',1),
    ('accurate',1),('khong lien quan',1),('không liên quan',1),
    ('tin gia',0),('tin giả',0),('tin sai lech',0),('tin sai lệch',0),
    ('misinformation',0),('sai su that',0),('sai sự thật',0),
]
REV_STANCE = {'ung ho':0,'ủng hộ':0,'support':0,'tan thanh':0,'tán thành':0,
    'phan doi':1,'phản đối':1,'oppose':1,'chong':1,'chống':1,
    'trung lap':2,'trung lập':2,'neutral':2}
REV_SENTIMENT = {'tieu cuc':0,'tiêu cực':0,'negative':0,
    'trung tinh':1,'trung tính':1,'trung hin':1,'neutral':1,
    'trung lap':1,'trung lập':1,
    'tich cuc':2,'tích cực':2,'positive':2}

def build_prompt(text):
    return [{"role":"user","content":(
        f'Phân tích nội dung sau về vaccine:\n\n"{text}"\n\n'
        'QUY TẮC PHÂN LOẠI (bắt buộc tuân thủ):\n'
        '- Misinformation CHỈ được chọn 1 trong 2: "Tin gia" hoặc "Chinh xac". '
        'TUYỆT ĐỐI KHÔNG dùng từ khác. Nội dung không liên quan vaccine '
        'hoặc không có thông tin sai = "Chinh xac".\n'
        '- Stance CHỈ: "Ung ho" / "Phan doi" / "Trung lap".\n'
        '- Sentiment CHỈ: "Tieu cuc" / "Trung tinh" / "Tich cuc".\n\n'
        'Trả lời theo ĐÚNG cấu trúc: KẾT QUẢ trước, GIẢI THÍCH sau.\n'
        '=== KẾT QUẢ ===\n'
        '- Misinformation: <Tin gia HOẶC Chinh xac>\n'
        '- Stance: <Ung ho HOẶC Phan doi HOẶC Trung lap>\n'
        '- Sentiment: <Tieu cuc HOẶC Trung tinh HOẶC Tich cuc>\n'
        '=== GIẢI THÍCH ===\n'
        '<lý luận chi tiết bằng tiếng Việt>'
    )}]

def _mis_binary(seg):
    '''
    Misinfo nhị phân. Xử lý:
      1. Negation: nếu trong 25 ký tự TRƯỚC keyword 'tin gia/sai lệch' có
         'không/no/chẳng/chả' → đảo: phủ định Tin giả = Chính xác (1)
      2. Conjunction 'nhưng/tuy nhiên': lấy phần SAU (mệnh đề cuối)
    '''
    s = (seg or '').strip().lower()
    if not s: return -1, False
    # Bước 1: nếu có 'nhưng/tuy nhiên/song' → ưu tiên mệnh đề SAU
    for conj in [' nhưng ', ' tuy nhiên ', ' nhưng,', ' song ']:
        if conj in s:
            s = s.split(conj, 1)[1]
            break
    # Bước 2: match keyword + check negation
    NEG_WORDS = ['không', 'khong', 'chẳng', 'chả ', 'chưa ', 'no ']
    for kw, val in REV_MISINFO_ORDER:
        idx = s.find(kw)
        if idx == -1:
            continue
        # Check 25 ký tự TRƯỚC kw có phủ định?
        prefix = s[:idx]  # toàn bộ prefix trong mệnh đề (sau khi split nhưng/tuy nhiên)
        has_neg = any(neg in prefix for neg in NEG_WORDS)
        if has_neg:
            # Phủ định → đảo nhãn
            # 'không Tin giả' / 'không sai lệch' → Chính xác (1)
            # 'không Chính xác' → Tin giả (0) — hiếm gặp nhưng xử lý đúng
            return (1 - val), True
        return val, True
    return 1, True

def _match_longest(seg, rev):
    s = (seg or '').lower()
    for k in sorted(rev, key=len, reverse=True):
        if k in s:
            return rev[k], True
    return -1, False

def _parse_block(block_text):
    """Parse 1 block KẾT QUẢ chuẩn. Trả về (m, st, se, ok, n_found)."""
    lines = [l.strip() for l in block_text.split('\n')]
    def find(pfx):
        for ln in lines:
            if pfx in ln:
                return ln.split(pfx, 1)[-1]
        return None
    seg_m  = find('misinformation:')
    seg_st = find('stance:')
    seg_se = find('sentiment:')
    n = sum(1 for x in [seg_m, seg_st, seg_se] if x is not None)
    m,  mo  = _mis_binary(seg_m) if seg_m is not None else (-1, False)
    st, so  = _match_longest(seg_st, REV_STANCE) if seg_st is not None else (-1, False)
    se, seo = _match_longest(seg_se, REV_SENTIMENT) if seg_se is not None else (-1, False)
    return m, st, se, (mo and so and seo), n

import re as _re

def _seg_after_keyword(line, keyword):
    """
    Lấy đoạn QUYẾT ĐỊNH sau từ khoá task — BỎ ngoặc đơn TIÊU ĐỀ ngay sau keyword.
    Ví dụ: '**Misinformation (Tin gia):** Nội dung chính xác' → 'Nội dung chính xác'
    (KHÔNG nhầm '(Tin gia)' là nhãn vì đó là tên task).
    """
    low = line.lower()
    idx = low.find(keyword.rstrip(':'))  # tìm 'misinformation' (không có :)
    if idx == -1:
        return None
    after_kw = line[idx + len(keyword.rstrip(':')):]
    # BƯỚC 1: bỏ ngoặc đơn ngay sau keyword (đó là TÊN TASK)
    #   '** (Tin gia):** Nội dung' → '** :** Nội dung' → 'Nội dung'
    after_kw_clean = _re.sub(r'^[*\s]*\([^)]*\)', '', after_kw)
    # BƯỚC 2: lấy phần SAU dấu ':' (nếu có) — đó là nội dung quyết định
    if ':' in after_kw_clean:
        decision = after_kw_clean.split(':', 1)[1]
    else:
        decision = after_kw_clean
    # BƯỚC 3: nếu có '->' / '[' / 'kết luận' lấy phần SAU đó
    for marker in ['->', '→', 'kết luận:', 'ket luan:', 'phân loại:', 'phan loai:']:
        if marker in decision.lower():
            decision = decision.lower().split(marker, 1)[1][:120]
            break
    # Lấy '[Nhãn]' nếu có
    mt = _re.search(r'\[([^\]]{1,40})\]', decision)
    if mt:
        return mt.group(1)
    return decision[:200]

def parse_output(text):
    t = (text or "")
    t_low = t.lower()

    # ---------- LAYER 1: TÁCH block KẾT QUẢ chuẩn, chọn block TỐT NHẤT ----------
    markers = list(_re.finditer(
        r'(?:=== kết quả ===|=== ket qua ===|^kết quả:|^ket qua:)',
        t_low, _re.M))
    if markers:
        blocks = []
        for i, mt in enumerate(markers):
            start = mt.end()
            end = markers[i+1].start() if i+1 < len(markers) else len(t_low)
            seg = t_low[start:end]
            for gm in ['=== giải thích ===','=== giai thich ===','giải thích:','giai thich:']:
                if gm in seg:
                    seg = seg.split(gm, 1)[0]; break
            blocks.append(seg)
        best = None
        for blk in blocks:
            res = _parse_block(blk)
            if best is None or (res[3] and not best[3]) or \
               (res[3]==best[3] and res[4] > best[4]):
                best = res
        if best and best[3]:
            return best[0], best[1], best[2], True

    # ---------- LAYER 2: văn xuôi không có block KẾT QUẢ ----------
    # FIX: dùng _seg_after_keyword (bỏ ngoặc đơn TIÊU ĐỀ task)
    lines = t.split('\n')
    seg_m = seg_st = seg_se = None
    for ln in lines:
        if 'misinformation' in ln.lower() and seg_m is None and len(ln) < 300:
            seg_m = _seg_after_keyword(ln, 'misinformation:')
        if 'stance' in ln.lower() and seg_st is None and len(ln) < 300:
            seg_st = _seg_after_keyword(ln, 'stance:')
        if 'sentiment' in ln.lower() and seg_se is None and len(ln) < 300:
            seg_se = _seg_after_keyword(ln, 'sentiment:')
    m,  mo  = _mis_binary(seg_m) if seg_m is not None else (-1, False)
    st, so  = _match_longest(seg_st, REV_STANCE) if seg_st is not None else (-1, False)
    se, seo = _match_longest(seg_se, REV_SENTIMENT) if seg_se is not None else (-1, False)
    if mo and so and seo:
        return m, st, se, True

    # ---------- LAYER 3: accept ≥2/3 nhãn ----------
    if (mo + so + seo) >= 2:
        return m, st, se, True

    return m, st, se, False

# Sanity tests
assert _mis_binary(' tin gia')[0]==0
assert _mis_binary(' chinh xac')[0]==1
assert _mis_binary(' khong tin gia')[0]==1
print("✅ Parser v3 ANSWER-FIRST PASS — FIX false-positive '(Tin gia)' tiêu đề task")
print("   Layer 2 v3: bỏ ngoặc đơn NGAY SAU keyword (tên task tiếng Việt)")
print("   Chỉ parse nhãn từ phần SAU dấu ':' (nội dung quyết định)")

"""### Bước 4: Batch Inference — GEN tokens thích nghi"""

# [B-CELL 4] BATCH Inference — GEN tokens THÍCH NGHI (min/max + early-stop)
from transformers import StoppingCriteria, StoppingCriteriaList
from tqdm import tqdm
import time as _t

with open(TEST_PATH, 'r', encoding='utf-8') as fh:
    test_data = [json.loads(l) for l in fh]
print(f'📦 Loaded {len(test_data)} samples')

done_ids = set()
if os.path.exists(INFERENCE_OUT):
    with open(INFERENCE_OUT) as f:
        for line in f:
            try: done_ids.add(json.loads(line)['id'])
            except: pass
    print(f'♻️  Resume: {len(done_ids)} done')

model.config.use_cache = True
_txt_tok.padding_side = 'left'

# Early-stop: cắt NGAY khi mọi mẫu trong batch đã sinh đủ 3 nhãn
# → câu ngắn dừng sớm (~200 tok), câu dài được tới GEN_MAX_NEW_TOKENS
class StopWhenAllLabeled(StoppingCriteria):
    def __init__(self, tok, plen, bs):
        self.tok, self.plen, self.done = tok, plen, [False]*bs
        self.n_gen = 0
    def __call__(self, input_ids, scores, **kw):
        self.n_gen += 1
        if self.n_gen < GEN_MIN_NEW_TOKENS:   # SÀN: chưa cho dừng quá sớm
            return False
        for i in range(input_ids.shape[0]):
            if self.done[i]: continue
            g = self.tok.decode(input_ids[i][self.plen:],
                                skip_special_tokens=True).lower()
            if ('misinformation:' in g and 'stance:' in g
                    and 'sentiment:' in g):
                self.done[i] = True
        return all(self.done)

pending = [r for r in test_data
           if r.get('id', r.get('post_id','')) not in done_ids]
print(f'📊 Còn {len(pending)} samples — batch={BATCH_SIZE_INF}, '
      f'GEN thích nghi [{GEN_MIN_NEW_TOKENS}..{GEN_MAX_NEW_TOKENS}]')

_t0 = _t.time()
with open(INFERENCE_OUT, 'a', encoding='utf-8') as out_f:
    for b0 in tqdm(range(0, len(pending), BATCH_SIZE_INF),
                   desc='Batch inference'):
        batch_rows = pending[b0 : b0 + BATCH_SIZE_INF]
        prompts = []
        for row in batch_rows:
            txt  = row.get('text_cleaned') or row.get('text') or ''
            msgs = build_prompt(txt)
            ps   = tokenizer.apply_chat_template(
                       msgs, tokenize=False, add_generation_prompt=True)
            prompts.append(ps)
        enc = tokenizer(text=prompts, return_tensors='pt',
                        padding=True, truncation=True,
                        max_length=MAX_SEQ_LEN - GEN_MAX_NEW_TOKENS).to('cuda')
        plen = enc['input_ids'].shape[1]
        stopper = StoppingCriteriaList([
            StopWhenAllLabeled(_txt_tok, plen, len(batch_rows))])

        with torch.no_grad():
            out = model.generate(
                **enc,
                max_new_tokens     = GEN_MAX_NEW_TOKENS,  # TRẦN
                min_new_tokens     = GEN_MIN_NEW_TOKENS,   # SÀN
                do_sample          = False,
                repetition_penalty = 1.1,
                pad_token_id       = PAD_ID,
                stopping_criteria  = stopper,
            )
        for i, row in enumerate(batch_rows):
            gen = tokenizer.decode(out[i][plen:], skip_special_tokens=True)
            m, st, se, ok = parse_output(gen)
            sid = row.get('id', row.get('post_id', ''))
            ids = row.get('standardized_ids')
            if not ids or len(ids) < 3: ids = [-1,-1,-1]
            rec = {'id': sid, 'true_m': ids[0], 'true_st': ids[1],
                   'true_se': ids[2], 'pred_m': m, 'pred_st': st,
                   'pred_se': se, 'parse_ok': ok,
                   'gen_len': len(out[i])-plen, 'reasoning': gen[:800]}
            out_f.write(json.dumps(rec, ensure_ascii=False) + '\n')
        out_f.flush()

_dur = int(_t.time()-_t0)
_recs = [json.loads(l) for l in open(INFERENCE_OUT)]
_ok = sum(1 for r in _recs if r['parse_ok'])
rate = _ok/len(_recs)*100
import numpy as _np
_glens = [r.get('gen_len',0) for r in _recs]
print(f'\n✅ Inference {_dur//60}m{_dur%60}s — {INFERENCE_OUT}')
print(f'   Parse OK: {_ok}/{len(_recs)} ({rate:.1f}%)')
print(f'   GEN tokens thực tế: mean={_np.mean(_glens):.0f}, '
      f'max={max(_glens)} (thích nghi: ngắn dừng sớm, dài dùng nhiều)')
if rate < 70:
    print('   ⚠️  Parse rate < 70%. 3 mẫu:')
    for r in _recs[:3]: print(f'   ─ {r["reasoning"][:400]}\n')
else:
    print('   ✅ Parse rate đạt — đáng tin cho luận văn')

"""### Bước 5: Evaluation — Macro F1 & Report"""

# [CELL 12] Classification Report + Macro F1 + Self-consistency analysis
from sklearn.metrics import classification_report, f1_score, confusion_matrix
import numpy as np

records = []
with open(INFERENCE_OUT, 'r') as f:
    for line in f:
        try: records.append(json.loads(line))
        except: pass
if not records:
    raise RuntimeError(f"❌ Không có records trong {INFERENCE_OUT}")

parse_fails = sum(1 for r in records if not r['parse_ok'])
print(f"📊 {len(records)} samples | Parse fail: {parse_fails} "
      f"({parse_fails/len(records)*100:.1f}%)")
print('='*60)

results = {}
task_configs = [
    ('misinfo',   'true_m',  'pred_m',  'agree_m',
     [HC_MISINFO[i]   for i in range(N_CLASSES['misinfo'])]),
    ('stance',    'true_st', 'pred_st', 'agree_st',
     [HC_STANCE[i]    for i in range(N_CLASSES['stance'])]),
    ('sentiment', 'true_se', 'pred_se', 'agree_se',
     [HC_SENTIMENT[i] for i in range(N_CLASSES['sentiment'])]),
]
for task, tk, pk, ak, labels in task_configs:
    valid = [(r[tk], r[pk], r.get(ak, 1.0))
             for r in records if r[tk] != -1 and r[pk] != -1]
    if not valid:
        print(f"⚠️  {task}: không có dữ liệu hợp lệ"); continue
    y_true = [v[0] for v in valid]
    y_pred = [v[1] for v in valid]
    n = len(labels)
    macro_f1 = f1_score(y_true, y_pred, average='macro',
                        labels=list(range(n)), zero_division=0)
    results[task] = {'macro_f1': round(macro_f1, 4),
                     'y_true': y_true, 'y_pred': y_pred}
    print(f"\n📌 {task.upper()} (n={len(y_true)}) — Macro F1: {macro_f1:.4f}")
    print(classification_report(y_true, y_pred, labels=list(range(n)),
                                target_names=labels, zero_division=0))
    # Insight: accuracy của mẫu high-agreement vs low-agreement
    hi = [(t,p) for t,p,a in valid if a >= 0.99]
    lo = [(t,p) for t,p,a in valid if a < 0.99]
    if hi and lo:
        acc_hi = np.mean([t==p for t,p in hi])
        acc_lo = np.mean([t==p for t,p in lo])
        print(f"   🔬 High-agreement (n={len(hi)}): acc={acc_hi:.2%} | "
              f"Low-agreement (n={len(lo)}): acc={acc_lo:.2%}")

print('\n' + '='*60 + '\n📊 MACRO F1 SUMMARY:')
for task, res in results.items():
    print(f'   {task:<12}: {res["macro_f1"]:.4f}')

"""### Bước 6: 🔗 Export gemma_v3_results.json (cho Benchmark Report)"""

# ════════════════════════════════════════════════════════════════════════
# 📑 INTEROP CONTRACT — gemma_v3_results.json (schema chuẩn 3 notebooks)
# ════════════════════════════════════════════════════════════════════════
# [CELL 13] Export gemma_v3_results.json
import datetime, os

def per_class_f1_support(y_true, y_pred, n_classes):
    f1s, sups = [], []
    for c in range(n_classes):
        yt = [1 if y == c else 0 for y in y_true]
        yp = [1 if y == c else 0 for y in y_pred]
        f1s.append(round(f1_score(yt, yp, zero_division=0), 4))
        sups.append(int(sum(yt)))
    return f1s, sups

parse_fails = sum(1 for r in records if not r['parse_ok'])
benchmark = {
    "model":              "gemma-4-4b-xai",
    "timestamp":          datetime.datetime.now().isoformat(),
    "total_samples":      len(records),
    "parse_failure_rate": round(parse_fails / len(records), 4),
}
for task, n in N_CLASSES.items():
    if task not in results: continue
    f1s, sups = per_class_f1_support(results[task]['y_true'],
                                      results[task]['y_pred'], n)
    benchmark[task] = {"macro_f1": results[task]['macro_f1'],
                       "per_class": f1s, "support": sups}

# Save to model dir AND /kaggle/working root (interop discovery)
# Notebook B không có MODELS_SAVE_DIR (đó là biến của Notebook A)
# Lưu vào /kaggle/working/ (root) — chuẩn interop cho benchmark report
for _p in ["/kaggle/working/gemma_v3_results.json"]:
    with open(_p, 'w', encoding='utf-8') as f:
        json.dump(benchmark, f, indent=2, ensure_ascii=False)

import shutil as _sh
if os.path.exists(INFERENCE_OUT) and \
   INFERENCE_OUT != "/kaggle/working/gemma_inference_results_v3.jsonl":
    _sh.copy(INFERENCE_OUT, "/kaggle/working/gemma_inference_results_v3.jsonl")

for task, n in N_CLASSES.items():
    if task in benchmark:
        assert len(benchmark[task]['per_class']) == n, f"per_class len: {task}"
        assert len(benchmark[task]['support'])   == n, f"support len: {task}"

print(f"✅ Saved: /kaggle/working/gemma_v3_results.json")
print(json.dumps(benchmark, indent=2, ensure_ascii=False))
print("\n✅ Schema validation OK")

"""### Bước 7: Confusion Matrix"""

# [CELL 14] Confusion Matrix (Taxonomy v3)
import matplotlib.pyplot as plt, matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'
from sklearn.metrics import confusion_matrix

task_plot_configs = [
    ('misinfo',   [HC_MISINFO[i]   for i in range(N_CLASSES['misinfo'])],  'Blues'),
    ('stance',    [HC_STANCE[i]    for i in range(N_CLASSES['stance'])],   'Greens'),
    ('sentiment', [HC_SENTIMENT[i] for i in range(N_CLASSES['sentiment'])],'Oranges'),
]
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Gemma-4 XAI — Confusion Matrix (Gold Test Set, n=186)',
             fontsize=14, fontweight='bold')
for ax, (task, labels, cmap) in zip(axes, task_plot_configs):
    if task not in results:
        ax.set_title(f'{task} — no data'); continue
    n  = len(labels)
    cm = confusion_matrix(results[task]['y_true'], results[task]['y_pred'],
                          labels=list(range(n)))
    im = ax.imshow(cm, cmap=cmap)
    ax.set_xticks(range(n)); ax.set_yticks(range(n))
    ax.set_xticklabels(labels, rotation=30, ha='right', fontsize=9)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel('Predicted'); ax.set_ylabel('True')
    ax.set_title(f'{task.capitalize()}\nMacro F1 = {results[task]["macro_f1"]:.4f}',
                 fontweight='bold')
    for i in range(n):
        for j in range(n):
            ax.text(j, i, str(cm[i,j]), ha='center', va='center', fontsize=11,
                    color='white' if cm[i,j] > cm.max()/2 else 'black')
    plt.colorbar(im, ax=ax)
plt.tight_layout()
plt.savefig('/kaggle/working/gemma_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Saved: /kaggle/working/gemma_confusion_matrix.png")

"""### (Optional) Bước 8: Quick Test 3 mẫu"""

# [CELL 16] Quick Test — 3 mẫu điển hình
test_samples = [
    ("Ko tiêm mũi nào hết. Cha mẹ thời nay bị doạ cho sợ hãi.",
     "Tin giả | Phản đối | Tiêu cực"),
    ("Mình vừa tiêm xong mũi 2, bs bảo vx an toàn, không lo phản ứng phụ.",
     "Chính xác | Ủng hộ | Tích cực"),
    ("Bé nhà tôi tiêm 5 trong 1 xong bị sốt 38.5, có sao không ạ?",
     "Chính xác | Trung lập | Tiêu cực"),
]
model.config.use_cache = True
print('🧪 QUICK TEST — 3 mẫu điển hình\n')
for i, (text, expected) in enumerate(test_samples):
    msgs = build_prompt(text)
    ps   = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
    # ✅ text= KEYWORD (Gemma4Processor)
    inp  = tokenizer(text=ps + "Lý luận:\n", return_tensors="pt").to("cuda")
    with torch.no_grad():
        out = model.generate(**inp, max_new_tokens=200, temperature=0.1,
                             do_sample=True, pad_token_id=PAD_ID)
    gen = tokenizer.decode(out[0][inp['input_ids'].shape[1]:], skip_special_tokens=True)
    m, st, se, ok = parse_output(gen)
    m_str  = HC_MISINFO.get(m,   f'?({m})')
    st_str = HC_STANCE.get(st,   f'?({st})')
    se_str = HC_SENTIMENT.get(se, f'?({se})')
    print(f'[{i+1}] {text[:70]}')
    print(f'  Expected : {expected}')
    print(f'  Predicted: {m_str} | {st_str} | {se_str} (parse_ok={ok})')
    print(f'  Reasoning: {gen[:150]}...\n')

"""---
## ✅ NOTEBOOK B HOÀN TẤT

Output: **`gemma_v3_results.json`** (schema chuẩn interop)

### Bước tiếp theo
→ Notebook benchmark report tự động pull file này khi add Notebook B
làm input. Xem hướng dẫn wiring trong `vaccinenlp-model-benchmark-report`.

### Tiết kiệm quota
Lần sau chỉ cần chạy lại Notebook B (~1h) để thử parser/prompt mới —
KHÔNG cần chạy lại Notebook A (train).

"""