# -*- coding: utf-8 -*-
"""Gemma E4B IT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/inhlqunhphng/gemma-e4b-it.85b609cc-20c3-4c43-81f8-1706d94c9366.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T182005Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D850554f2b489e3ebb7320521d70ab616f537b2098eded532359421121077eb38b70ea16c1b29bb25fd74f5fdf29d61bbb5651167508df6efef0032ffb3e79f0783b4d4a91cd60bb6dd6dc32027a5eaaeae026055b2f61a3eda9af3e13f74b5acfbb5ef6bb745844fd7f052755913669bf174db961d84e1ab429a5db8e79ec7b56f0652ff9f16458d8ebc263b8ccfb8282627392058dac76f54a9d75aed98f96c1a9aae7492023a91a4e2474d44938b6d478f38f0bb85038f96c765b32684eab2d602e92ab36be19381eefe54c7947f3ddfb4e37500756aaee1109a2fa4a1a79d1b22d66456a0fd17b518a99a1c81c59367bd9ae698277c29ee4570f21482fa26
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
try:
    import kagglehub
    inhlqunhphng_vaccinenlp_clean_data_path = kagglehub.dataset_download('inhlqunhphng/vaccinenlp-clean-data')
    print('Data source import complete.')
except:
    print('Kagglehub not found, skipping Kaggle-specific download.')

import subprocess, sys

subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y",
                "sentence-transformers", "torchaudio", "transformers", "trl"],
               capture_output=True)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "git+https://github.com/huggingface/transformers.git"], check=True)
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "git+https://github.com/huggingface/trl.git"], check=True)
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "peft>=0.19.0", "accelerate>=1.2.1",
                "bitsandbytes>=0.45.0", "torchvision>=0.19.0"], check=True)

print("✅ Cài đặt hoàn tất! Vào Menu > Run > Restart Session, rồi chạy từ Cell 2.")

import os
import torch
from huggingface_hub import login
from datasets import load_dataset
from transformers import AutoModelForImageTextToText, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer

from kaggle_secrets import UserSecretsClient
try:
    user_secrets = UserSecretsClient()
    VaccineNLP_TOKEN = user_secrets.get_secret("VaccineNLP")
    login(token=VaccineNLP_TOKEN)
    print("✅ Đăng nhập HuggingFace thành công!")
except Exception as e:
    print(f"⚠️ Không tìm thấy VaccineNLP: {e}")

# ── Paths (Linh hoạt: Local / Kaggle) ──────────────────────────────────────
from src.common import paths

TRAIN_PATH      = paths.SILVER_LABELS_DIR / "train_set_final.jsonl"
TEST_PATH       = paths.GOLD_DATA_DIR / "benchmark_test_set.jsonl"
MODELS_SAVE_DIR = paths.MODEL_DIR / "gemma_qlora_xai"
os.makedirs(MODELS_SAVE_DIR, exist_ok=True)

for path in [TRAIN_PATH, TEST_PATH]:
    print(("✅" if os.path.exists(path) else "❌ KHÔNG TÌM THẤY") + f": {path}")
print(f"\n📁 Lưu model: {MODELS_SAVE_DIR}")

model_id = "google/gemma-4-E4B-it"
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

misinfo_map   = {0: "Không liên quan", 1: "Tin giả", 2: "Chính xác"}
stance_map    = {0: "Ủng hộ", 1: "Phản đối", 2: "Trung lập", 3: "Không rõ"}
sentiment_map = {0: "Tiêu cực", 1: "Trung tính", 2: "Tích cực"}

def format_xai_prompt(row):
    text = row.get('text_cleaned') or row.get('text') or row.get('text_original') or str(list(row.values())[0])
    reasoning = row.get('llm_reasoning', 'Phân tích dựa trên ngữ cảnh.')
    ids = row.get('standardized_ids')
    if not ids or len(ids) != 3: ids = [0, 3, 1]

    user_prompt = (
        f"You are an Explainable AI in Public Health. Analyze the text, "
        f"provide your reasoning first, and then the structured labels.\n\nVăn bản: {text}"
    )
    assistant_response = (
        f"Lý luận: {reasoning}\n"
        f"Kết quả: {misinfo_map.get(ids[0], 'Không liên quan')} | "
        f"{stance_map.get(ids[1], 'Không rõ')} | "
        f"{sentiment_map.get(ids[2], 'Trung tính')}"
    )
    messages = [
        {"role": "user",  "content": user_prompt},
        {"role": "model", "content": assistant_response}
    ]
    return {"text": tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)}

print("Đang tải và map dữ liệu...")
train_ds = load_dataset("json", data_files=TRAIN_PATH, split="train").map(format_xai_prompt)
test_ds  = load_dataset("json", data_files=TEST_PATH,  split="train").map(format_xai_prompt)
print("✅ Format Data hoàn tất!")
print(train_ds[0]['text'][:300] + "...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

# In top-level modules để debug khi cần
top_modules = sorted(set(n.split('.')[0] for n, _ in model.named_modules() if n))
print("Top-level modules:", top_modules)

# FIX: PEFT >= 0.19.0 với "all-linear" + exclude_modules tự bỏ qua ClippableLinear
# Regex "language_model.*" bị lỗi vì tên module thực tế có thể khác nhau
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules="all-linear",
    exclude_modules=["vision_tower", "audio_tower", "multi_modal_projector"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, peft_config)
model.gradient_checkpointing_enable()
model.print_trainable_parameters()
print("✅ Khởi tạo QLoRA hoàn tất.")

from trl import SFTConfig

sft_config = SFTConfig(
    output_dir=MODELS_SAVE_DIR,
    max_length=256,
    dataset_text_field="text",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=10,
    num_train_epochs=2,
    save_strategy="epoch",
    eval_strategy="no",                # FIX OOM: tắt eval sau mỗi epoch
    optim="paged_adamw_8bit",
    bf16=True,
    max_grad_norm=0.3,
    warmup_steps=10,
    report_to="none",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    ddp_find_unused_parameters=False
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    processing_class=tokenizer,
    args=sft_config,
)

print("🚀 Bắt đầu huấn luyện...")
torch.cuda.empty_cache()
trainer.train()

trainer.model.save_pretrained(f"{MODELS_SAVE_DIR}/final_model")
tokenizer.save_pretrained(f"{MODELS_SAVE_DIR}/final_model")
print(f"💾 Đã lưu model tại: {MODELS_SAVE_DIR}/final_model")