# -*- coding: utf-8 -*-
"""VaccineNLP Gemma-4 QLoRA Multitask

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/inhlqunhphng/vaccinenlp-gemma-4-qlora-multitask.95435b96-1f74-481d-8763-c4f0f7dccd6e.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260512/auto/storage/goog4_request%26X-Goog-Date%3D20260512T033354Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D66e003da9be5823fe18a8e0bf7b20987a297e51658ca01304714d4a1bf4709ed5378d952ed80a147caf873b6e934d37849a86b2de7bc892301b21c22b26c13d14a977597fcb35818072d11caeaf4d79e92f64ad06f814b1a3ceb6427e3c39d498752417d69b5a2b683f9e9725f38ec200477fca0c658d56501664f2707afd540dde6eb31159256030d10b43a5408bd65e18370e7abfd2561647f919673677c6aadde804aeb82652b43de0a3e57580d059cfa03690b74e0c788b99e5ecffc818dbc12f59d7d91dfcdc6538513a99ec04abe2fd0609b3504645f7ca3e3091d3d6b27ef9d54d57f47066b849e3a9ef47d6d42830296dea9ba93db0db7e1d4e54884
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
inhlqunhphng_vaccinenlp_clean_data_path = kagglehub.dataset_download('inhlqunhphng/vaccinenlp-clean-data')

print('Data source import complete.')

"""# 💉 Gemma-4 QLoRA Training + Inference & Evaluation
## VaccineNLP Thesis — Kiến trúc Gemma-4 Teacher (XAI)

**MSSV:** 2211090016 | **Môi trường:** Kaggle T4 GPU | **Framework:** Unsloth

### 📋 Workflow notebook (2 Phase):
- **Phase A** — QLoRA Fine-tuning: Huấn luyện Gemma-4 4B với dữ liệu Silver
- **Phase B** — Inference & Evaluation: Đánh giá trên Gold Test Set (186 mẫu)

> ✅ **Notebook này tương thích với chế độ "Save & run all" của Kaggle.**
> Toàn bộ notebook chạy trên **2x T4 GPU (16GB)** — không cần restart thủ công.

"""

# [CELL 1] Cài đặt Unsloth & Xử lý Numpy
# ✅ FIX: Di chuyển pip install lên đầu tiên để tránh lỗi mid-session upgrade

import os, subprocess, sys

def run_silent(cmd):
    print(f"🏃 Running: {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"⚠️  STDERR: {result.stderr[-300:]}")
    return result.returncode

# 1. Gỡ cài đặt numpy cũ nếu cần hoặc cài đè ngay lập tức
# Unsloth cần numpy>=2.0. Kaggle có 2.0.2. Chúng ta sẽ cài bản pinned để tránh upgrade lên bản dev/beta
print("📦 Cài đặt Unsloth [Kaggle-new]...")
# Sử dụng git install để có bản mới nhất fix lỗi Gemma-4
run_silent('pip install "unsloth[kaggle-new] @ git+https://github.com/unslothai/unsloth.git" --quiet')

# 2. Kiểm tra lại numpy
try:
    import numpy as np
    print(f"✅ Numpy version: {np.__version__}")
except RuntimeError as e:
    print(f"❌ Lỗi Numpy: {e}")
    print("   → Đang thử fix bằng cách reload...")
    import importlib
    importlib.reload(np)

# 3. Kiểm tra GPU
print("🖥️  GPU Info:")
subprocess.run("nvidia-smi -L", shell=True)

try:
    from unsloth import FastModel
    print("✅ Unsloth FastModel import OK")
except ImportError as e:
    print(f"❌ Import lỗi: {e}")

"""---
## ⚙️ Phase A — QLoRA Fine-tuning
### Bước 1: Imports & Kiểm tra GPU

"""

# [CELL 2] Imports & GPU diagnostics
import os, gc, json, glob, datetime, shutil
import torch
from huggingface_hub import login, HfApi
from datasets import load_dataset
from unsloth import FastModel
from unsloth.chat_templates import get_chat_template, train_on_responses_only
from trl import SFTTrainer, SFTConfig
from IPython.display import FileLink, display

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

# GPU info
if torch.cuda.is_available():
    props = torch.cuda.get_device_properties(0)
    total_gb = props.total_memory / 1e9
    print(f"🖥️  GPU: {props.name}")
    print(f"💾 VRAM: {total_gb:.1f} GB")
    print(f"🔢 CUDA: {torch.version.cuda}")
    print(f"⚡ BF16: {'✅' if torch.cuda.is_bf16_supported() else '❌ (dùng FP16)'}")
    if total_gb < 14:
        print("⚠️  CẢNH BÁO: VRAM < 14GB — có thể OOM khi train")
else:
    raise RuntimeError("❌ Không tìm thấy GPU — Vui lòng bật GPU T4 trong Kaggle Settings")

"""### Bước 2: Cấu hình tập trung"""

# [CELL 3] CẤU HÌNH TẬP TRUNG — Chỉnh sửa tại đây, KHÔNG sửa ở các cell khác

# --- Paths ---
try:
    TRAIN_PATH = glob.glob("/kaggle/input/**/train_v2_seg.jsonl", recursive=True)[0]
    TEST_PATH  = glob.glob("/kaggle/input/**/benchmark_test_set.jsonl", recursive=True)[0]
except:
    TRAIN_PATH = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data/05_model_ready/train_v2_seg.jsonl"
    TEST_PATH  = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data/03_processed/benchmark_test_set.jsonl"

MODELS_SAVE_DIR = "/kaggle/working/gemma_qlora_xai"
INFERENCE_OUT   = "/kaggle/working/gemma_inference_results_v2.jsonl"
RESULTS_JSON    = "/kaggle/working/gemma_benchmark_results.json"
HF_REPO_ID      = "quynhphuong1209/gemma-4-E4B-unsloth-vaccine-xai"

# --- Model ---
BASE_MODEL      = "unsloth/gemma-4-E4B-it"
MAX_SEQ_LEN     = 1024
LOAD_IN_4BIT    = True

# --- LoRA ---
LORA_R          = 16
LORA_ALPHA      = 16
LORA_DROPOUT    = 0.0

# --- Training ---
BATCH_SIZE      = 2
GRAD_ACCUM      = 4
WARMUP_STEPS    = 10
TRAIN_EPOCHS    = 2
LEARNING_RATE   = 2e-4
WEIGHT_DECAY    = 0.01
LR_SCHEDULER    = "cosine"
SEED            = 42

# --- Label Maps ---
MISINFO_MAP  = {0: 'Không liên quan', 1: 'Tin giả', 2: 'Chính xác'}
STANCE_MAP   = {0: 'Ủng hộ', 1: 'Phản đối', 2: 'Trung lập', 3: 'Không rõ'}
SENTIMENT_MAP= {0: 'Tiêu cực', 1: 'Trung tính', 2: 'Tích cực'}

os.makedirs(MODELS_SAVE_DIR, exist_ok=True)
print("✅ Config loaded")
print(f"   Train  : {TRAIN_PATH}")
print(f"   Test   : {TEST_PATH}")
print(f"   Output : {MODELS_SAVE_DIR}")
print(f"   HF repo: {HF_REPO_ID}")

"""### Bước 3: Load Gemma-4 + LoRA Config"""

# [CELL 4] Load Gemma-4 E4B + LoRA adapter
model, tokenizer = FastModel.from_pretrained(
    model_name     = BASE_MODEL,
    max_seq_length = MAX_SEQ_LEN,
    dtype          = None,
    load_in_4bit   = LOAD_IN_4BIT,
)

model = FastModel.get_peft_model(
    model,
    finetune_vision_layers     = False,
    finetune_language_layers   = True,
    finetune_attention_modules = True,
    finetune_mlp_modules       = True,
    r                          = LORA_R,
    lora_alpha                 = LORA_ALPHA,
    lora_dropout               = LORA_DROPOUT,
    bias                       = "none",
    use_gradient_checkpointing = "unsloth",
    random_state               = SEED,
)

total_params     = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✅ Model loaded: {BASE_MODEL}")
print(f"   Total params    : {total_params/1e6:.1f}M")
print(f"   Trainable params: {trainable_params/1e6:.1f}M ({100*trainable_params/total_params:.2f}%)")

"""### Bước 4: Chuẩn bị Dataset & Format Prompt"""

# [CELL 5] Dataset preparation + prompt formatting
from datasets import load_dataset

def get_chat_template(tokenizer, chat_template="gemma-4"):
    """Áp dụng chat template cho tokenizer."""
    if chat_template == "gemma-4":
        # Gemma-4 style template
        tokenizer.chat_template = "{% for message in messages %}" \
        "{% if message['role'] == 'user' %}" \
        "<start_of_turn>user\n{{ message['content'] }}<end_of_turn>\n" \
        "{% elif message['role'] == 'assistant' %}" \
        "<start_of_turn>model\n{{ message['content'] }}<end_of_turn>\n" \
        "{% endif %}" \
        "{% endfor %}"
    elif chat_template == "llama3":
        # Llama 3 style template
        tokenizer.chat_template = "{% for message in messages %}" \
        "{% if message['role'] == 'user' %}" \
        "<|start_header_id|>user<|end_header_id|>\n\n{{ message['content'] }}<|eot_id|>" \
        "{% elif message['role'] == 'assistant' %}" \
        "<|start_header_id|>assistant<|end_header_id|>\n\n{{ message['content'] }}<|eot_id|>" \
        "{% endif %}" \
        "{% endfor %}"
    else:
        # Mặc định sử dụng template của tokenizer
        pass

    return tokenizer

# Áp dụng chat template cho tokenizer từ CELL 4
tokenizer = get_chat_template(tokenizer, chat_template="gemma-4")

def format_prompt(row):
    """Chuyển row JSONL → conversation format cho Gemma-4 (XAI pattern)."""
    text      = row.get('text_cleaned') or row.get('text') or ''
    reasoning = row.get('llm_reasoning', 'Phân tích dựa trên ngữ cảnh.')
    ids       = row.get('standardized_ids') or [0, 2, 1]

    misinfo_label = MISINFO_MAP.get(ids[0], 'Không liên quan')
    stance_label  = STANCE_MAP.get(ids[1], 'Không rõ')
    senti_label   = SENTIMENT_MAP.get(ids[2], 'Trung tính')

    convo = [
        {
            "role": "user",
            "content": (
                f"Phân tích nội dung sau về vaccine:\n\n\"{text}\"\n\n"
                "Hãy:\n"
                "1. Lý luận từng bước về nội dung\n"
                "2. Phân loại theo 3 chiều:\n"
                "   - Misinformation: Không liên quan / Tin giả / Chính xác\n"
                "   - Stance: Ủng hộ / Phản đối / Trung lập / Không rõ\n"
                "   - Sentiment: Tiêu cực / Trung tính / Tích cực"
            )
        },
        {
            "role": "assistant",
            "content": (
                f"Lý luận:\n{reasoning}\n\n"
                f"Kết quả:\n"
                f"- Misinformation: {misinfo_label}\n"
                f"- Stance: {stance_label}\n"
                f"- Sentiment: {senti_label}"
            )
        }
    ]
    return tokenizer.apply_chat_template(convo, tokenize=False)

# Load dataset
raw_ds = load_dataset("json", data_files={"train": TRAIN_PATH}, split="train")
split  = raw_ds.train_test_split(test_size=0.1, seed=SEED)
train_ds = split["train"].map(lambda r: {"text": format_prompt(r)}, num_proc=2)
eval_ds  = split["test"].map(lambda r: {"text": format_prompt(r)}, num_proc=2)

print(f"✅ Dataset ready — Train: {len(train_ds)}, Eval: {len(eval_ds)}")

"""### Bước 5: Huấn luyện QLoRA"""

# [CELL 6] Với train_on_responses_only - ĐÃ SỬA PATTERN ĐÚNG
from trl import SFTTrainer, SFTConfig
from unsloth import train_on_responses_only
import torch

trainer = SFTTrainer(
    model         = model,
    tokenizer     = tokenizer,
    train_dataset = train_ds,
    eval_dataset  = eval_ds,
    args = SFTConfig(
        output_dir                  = MODELS_SAVE_DIR,
        dataset_text_field          = "text",
        max_length                  = MAX_SEQ_LEN,
        per_device_train_batch_size = BATCH_SIZE,
        per_device_eval_batch_size  = 1,
        gradient_accumulation_steps = GRAD_ACCUM,
        eval_accumulation_steps     = 1,
        warmup_steps                = WARMUP_STEPS,
        num_train_epochs            = TRAIN_EPOCHS,
        learning_rate               = LEARNING_RATE,
        weight_decay                = WEIGHT_DECAY,
        lr_scheduler_type           = LR_SCHEDULER,
        fp16                        = not torch.cuda.is_bf16_supported(),
        bf16                        = torch.cuda.is_bf16_supported(),
        logging_steps               = 10,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        load_best_model_at_end      = True,
        seed                        = SEED,
        report_to                   = "none",
    ),
)

# SỬA pattern đúng với Gemma template
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<end_of_turn>\n<start_of_turn>user\n",
    response_part    = "<end_of_turn>\n<start_of_turn>model\n",
)

print("🚀 Bắt đầu huấn luyện...")
train_result = trainer.train()
print(f"✅ Huấn luyện hoàn tất!")
print(f"   Loss cuối: {train_result.training_loss:.4f}")

# Lưu model
trainer.save_model(f"{MODELS_SAVE_DIR}/final_model")
tokenizer.save_pretrained(f"{MODELS_SAVE_DIR}/final_model")
print(f"✅ Model đã lưu: {MODELS_SAVE_DIR}/final_model")

"""### Bước 6: Lưu & Upload lên HuggingFace Hub"""

# [CELL 7] Nén model + push HuggingFace Hub
# ✅ FIX: HF push được wrap trong try/except — Phase B không phụ thuộc vào push thành công

# --- Nén để download ---
print("📦 Nén model để tải về...")
shutil.make_archive('/kaggle/working/gemma_vaccine_model', 'zip', f'{MODELS_SAVE_DIR}/final_model')
print("✅ Đã tạo: /kaggle/working/gemma_vaccine_model.zip")
display(FileLink('/kaggle/working/gemma_vaccine_model.zip'))

# --- Push lên HuggingFace Hub (không bắt buộc) ---
try:
    from kaggle_secrets import UserSecretsClient
    VaccineNLP_TOKEN = UserSecretsClient().get_secret("VaccineNLP")
    if VaccineNLP_TOKEN:
        login(token=VaccineNLP_TOKEN, add_to_git_credential=False)
        api = HfApi()
        api.upload_folder(
            folder_path = f"{MODELS_SAVE_DIR}/final_model",
            repo_id     = HF_REPO_ID,
            repo_type   = "model",
        )
        print(f"✅ Pushed lên HuggingFace: {HF_REPO_ID}")
    else:
        print("⚠️  HF_TOKEN rỗng — bỏ qua push")
except Exception as e:
    print(f"⚠️  HF push thất bại (không ảnh hưởng Phase B): {e}")

print(f"\n📁 Model local: {MODELS_SAVE_DIR}/final_model")

"""---
## 🔄 VRAM Cleanup — Bắt buộc giữa Phase A và Phase B

> Giải phóng VRAM trước khi load model inference. Bỏ qua bước này sẽ gây **OOM error**.

"""

# [CELL 8] ⚠️ BẮT BUỘC CHẠY trước Phase B
# ✅ FIX: Dùng globals() thay dir() — đáng tin cậy hơn khi "Save & run all"

print("🔄 Giải phóng VRAM...")

_to_delete = ['trainer', 'train_ds', 'eval_ds', 'model', 'tokenizer']
for _var in _to_delete:
    if _var in globals():
        del globals()[_var]
        print(f"   🗑️  Đã xóa: {_var}")

gc.collect()
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

allocated = torch.cuda.memory_allocated() / 1e9
reserved  = torch.cuda.memory_reserved()  / 1e9
print(f"\n✅ VRAM sau cleanup:")
print(f"   Allocated: {allocated:.2f} GB")
print(f"   Reserved:  {reserved:.2f} GB")
print("\n➡️  Sẵn sàng chạy Phase B — Inference & Evaluation")

"""---
## 📊 Phase B — Inference & Evaluation
### Đánh giá Gemma-4 XAI trên Gold Test Set (186 mẫu)

Model được load **trực tiếp từ local** (`/kaggle/working/gemma_qlora_xai/final_model`).
Không phụ thuộc vào HuggingFace push — an toàn khi chạy tự động.

### Bước 7: Load Model cho Inference
"""

# [CELL 9] Load model từ LOCAL — không cần HF Hub
# ✅ FIX CHÍNH: Dùng model vừa train trong cùng session
#    → Không phụ thuộc vào HF push thành công
#    → Tốc độ load nhanh hơn (~5x so với download từ Hub)

import torch, json, gc, glob, os
from tqdm import tqdm
from unsloth import FastModel
from unsloth.chat_templates import get_chat_template

LOCAL_MODEL_PATH = f"{MODELS_SAVE_DIR}/final_model"

if not os.path.exists(LOCAL_MODEL_PATH):
    raise FileNotFoundError(
        f"❌ Không tìm thấy model tại: {LOCAL_MODEL_PATH}\n"
        f"   Phase A phải chạy thành công trước."
    )

model, tokenizer = FastModel.from_pretrained(
    model_name     = LOCAL_MODEL_PATH,
    max_seq_length = MAX_SEQ_LEN,
    load_in_4bit   = LOAD_IN_4BIT,
)
FastModel.for_inference(model)
tokenizer = get_chat_template(tokenizer, chat_template="gemma-4")

allocated = torch.cuda.memory_allocated() / 1e9
print(f"✅ Model loaded từ local: {LOCAL_MODEL_PATH}")
print(f"💾 VRAM used: {allocated:.2f} GB")

"""### Bước 8: Prompt Builder & Output Parser"""

# [CELL 10] Reverse label maps + build_prompt + parse_output

REV_MISINFO = {
    'không liên quan': 0, 'khong lien quan': 0, 'not relevant': 0, 'không có': 0,
    'tin giả': 1, 'tin gia': 1, 'sai lệch': 1, 'misinformation': 1,
    'chính xác': 2, 'chinh xac': 2, 'accurate': 2, 'no misinformation': 2,
}
REV_STANCE = {
    'ủng hộ': 0, 'ung ho': 0, 'support': 0, 'pro-vaccine': 0,
    'phản đối': 1, 'phan doi': 1, 'oppose': 1, 'anti-vaccine': 1,
    'trung lập': 2, 'trung lap': 2, 'neutral': 2,
    'không rõ': 3, 'khong ro': 3, 'unknown': 3, 'không xác định': 3,
}
REV_SENTIMENT = {
    'tiêu cực': 0, 'tieu cuc': 0, 'negative': 0,
    'trung tính': 1, 'trung tinh': 1, 'neutral': 1,
    'tích cực': 2, 'tich cuc': 2, 'positive': 2,
}

def build_prompt(text):
    return [{
        "role": "user",
        "content": (
            f"Phân tích nội dung sau về vaccine:\n\n\"{text}\"\n\n"
            "Hãy:\n"
            "1. Lý luận từng bước về nội dung\n"
            "2. Phân loại theo 3 chiều:\n"
            "   - Misinformation: Không liên quan / Tin giả / Chính xác\n"
            "   - Stance: Ủng hộ / Phản đối / Trung lập / Không rõ\n"
            "   - Sentiment: Tiêu cực / Trung tính / Tích cực"
        )
    }]

def parse_output(text):
    """Parse output → (misinfo_idx, stance_idx, sentiment_idx, parse_ok)."""
    text_l = text.lower()
    lines  = [l.strip() for l in text_l.split('\n')]

    def find_label(rev_map, prefix):
        for line in lines:
            if prefix in line:
                for key, val in rev_map.items():
                    if key in line:
                        return val, True
        return -1, False

    m, m_ok  = find_label(REV_MISINFO,   'misinformation:')
    st, s_ok = find_label(REV_STANCE,    'stance:')
    se, e_ok = find_label(REV_SENTIMENT, 'sentiment:')

    parse_ok = m_ok and s_ok and e_ok
    return m, st, se, parse_ok

print("✅ Parser ready — 4 nhãn stance đầy đủ (Ủng hộ/Phản đối/Trung lập/Không rõ)")

"""### Bước 9: Inference Loop (186 Gold Test Samples)"""

# [CELL 11] Inference loop — lưu progressive JSONL
# Resume support: bỏ qua samples đã xử lý nếu Kaggle timeout

found = glob.glob('/kaggle/input/**/benchmark_test_set.jsonl', recursive=True)
TEST_PATH_INF = found[0] if found else TEST_PATH

with open(TEST_PATH_INF, 'r', encoding='utf-8') as fh:
    test_data = [json.loads(l) for l in fh]

print(f'📦 Loaded {len(test_data)} samples từ: {TEST_PATH_INF}')
print(f'💾 Kết quả sẽ lưu tại: {INFERENCE_OUT}')

# Resume support
done_ids = set()
if os.path.exists(INFERENCE_OUT):
    with open(INFERENCE_OUT) as f:
        for line in f:
            try: done_ids.add(json.loads(line)['id'])
            except: pass
    print(f'♻️  Resume: đã có {len(done_ids)} samples — bỏ qua')

model.config.use_cache = True

with open(INFERENCE_OUT, 'a', encoding='utf-8') as out_f:
    for row in tqdm(test_data, desc="Inference"):
        sid = row.get('id', row.get('post_id', ''))
        if sid in done_ids:
            continue

        text = row.get('text_cleaned') or row.get('text') or ''
        msgs = build_prompt(text)
        prompt_str = tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True
        )
        forced_str = prompt_str + "Lý luận:\n"

        inputs = tokenizer(text=forced_str, return_tensors="pt").to("cuda")
        with torch.no_grad():
            out = model.generate(
                **inputs,
                max_new_tokens  = 1024,
                temperature     = 0.1,
                do_sample       = True,
                repetition_penalty = 1.1,
            )

        generated = tokenizer.decode(
            out[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True
        )
        m, st, se, parse_ok = parse_output(generated)

        ids = row.get('standardized_ids') or [-1, -1, -1]
        record = {
            'id':       sid,
            'true_m':   ids[0] if len(ids) > 0 else -1,
            'true_st':  ids[1] if len(ids) > 1 else -1,
            'true_se':  ids[2] if len(ids) > 2 else -1,
            'pred_m':   m,
            'pred_st':  st,
            'pred_se':  se,
            'parse_ok': parse_ok,
            'reasoning': generated[:500],
        }
        out_f.write(json.dumps(record, ensure_ascii=False) + '\n')
        out_f.flush()

print(f'\n✅ Inference hoàn tất — {INFERENCE_OUT}')

"""### Bước 10: Evaluation — Macro F1 & Classification Report"""

# [CELL 12] Classification Report + Macro F1
from sklearn.metrics import classification_report, f1_score, confusion_matrix
import numpy as np

records = []
with open(INFERENCE_OUT, 'r') as f:
    for line in f:
        try: records.append(json.loads(line))
        except: pass

print(f'📊 Đánh giá trên {len(records)} samples (target: 186)\n')

parse_fails = sum(1 for r in records if not r['parse_ok'])
print(f'⚠️  Parse Failure: {parse_fails}/{len(records)} = {parse_fails/len(records)*100:.1f}%')
print('='*60)

results = {}
task_configs = [
    ('misinfo',   'true_m',  'pred_m',  ['Không liên quan', 'Tin giả', 'Chính xác']),
    ('stance',    'true_st', 'pred_st', ['Ủng hộ', 'Phản đối', 'Trung lập', 'Không rõ']),
    ('sentiment', 'true_se', 'pred_se', ['Tiêu cực', 'Trung tính', 'Tích cực']),
]

for task, tk, pk, labels in task_configs:
    y_true = [r[tk] for r in records if r[tk] != -1 and r[pk] != -1]
    y_pred = [r[pk] for r in records if r[tk] != -1 and r[pk] != -1]
    if not y_true:
        print(f'⚠️  {task}: không có dữ liệu hợp lệ')
        continue
    macro_f1 = f1_score(y_true, y_pred, average='macro', zero_division=0)
    results[task] = {'macro_f1': round(macro_f1, 4)}
    print(f'\n📌 Task: {task.upper()}')
    print(classification_report(
        y_true, y_pred,
        target_names=labels[:max(y_true+y_pred)+1] if max(y_true+y_pred) < len(labels) else labels,
        zero_division=0
    ))

print('\n' + '='*60)
print('📊 MACRO F1 SUMMARY:')
for task, res in results.items():
    print(f'   {task:<12}: {res["macro_f1"]:.4f}')

"""### Bước 11: Export Benchmark Results JSON"""

# [CELL 13] Export kết quả ra JSON
import datetime

benchmark = {
    'model':               'gemma-4-4b-xai',
    'hf_repo':             HF_REPO_ID,
    'timestamp':           datetime.datetime.now().isoformat() + 'Z',
    'total_samples':       len(records),
    'parse_failure_rate':  round(parse_fails / len(records), 4),
    'misinfo':             results.get('misinfo',   {}),
    'stance':              results.get('stance',    {}),
    'sentiment':           results.get('sentiment', {}),
}

with open(RESULTS_JSON, 'w', encoding='utf-8') as f:
    json.dump(benchmark, f, indent=2, ensure_ascii=False)

print(f'✅ Kết quả đã lưu: {RESULTS_JSON}')
print(json.dumps(benchmark, indent=2, ensure_ascii=False))

"""### Bước 12: Confusion Matrix"""

# [CELL 14] Confusion matrix cho 3 tasks
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Gemma-4 XAI — Confusion Matrix (Gold Test Set, n=186)', fontsize=14, fontweight='bold')

task_plot_configs = [
    ('misinfo',   'true_m',  'pred_m',  ['Không\nliên quan', 'Tin giả', 'Chính xác'],              'Blues'),
    ('stance',    'true_st', 'pred_st', ['Ủng hộ', 'Phản đối', 'Trung lập', 'Không rõ'],            'Greens'),
    ('sentiment', 'true_se', 'pred_se', ['Tiêu cực', 'Trung tính', 'Tích cực'],                     'Oranges'),
]

for ax, (task, tk, pk, labels, cmap) in zip(axes, task_plot_configs):
    y_true = [r[tk] for r in records if r[tk] != -1 and r[pk] != -1]
    y_pred = [r[pk] for r in records if r[tk] != -1 and r[pk] != -1]
    n = len(labels)
    cm = confusion_matrix(y_true, y_pred, labels=list(range(n)))
    im = ax.imshow(cm, cmap=cmap)
    ax.set_xticks(range(n)); ax.set_yticks(range(n))
    ax.set_xticklabels(labels, fontsize=9); ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel('Predicted'); ax.set_ylabel('True')
    ax.set_title(f'{task.capitalize()}\nMacro F1={results.get(task,{}).get("macro_f1","N/A")}')
    for i in range(n):
        for j in range(n):
            ax.text(j, i, str(cm[i,j]), ha='center', va='center', fontsize=11,
                    color='white' if cm[i,j] > cm.max()/2 else 'black')
    plt.colorbar(im, ax=ax)

plt.tight_layout()
plt.savefig('/kaggle/working/confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Đã lưu: /kaggle/working/confusion_matrix.png")

"""### Bước 13: So sánh với PhoBERT-v2 & XLM-R"""

# [CELL 15] Bảng so sánh 3 mô hình
PHOBERT_F1 = {'misinfo': 0.4547, 'stance': 0.6608, 'sentiment': 0.7325}
XLMR_F1    = {'misinfo': 0.4572, 'stance': 0.6247, 'sentiment': 0.6918}
GEMMA_F1   = {k: results[k]['macro_f1'] for k in results}

print('='*65)
print('📊 BENCHMARK COMPARISON — Macro F1 Score (Gold Test Set, n=186)')
print('='*65)
print(f"{'Model':<25} {'Misinfo':>10} {'Stance':>10} {'Sentiment':>12} {'Avg':>8}")
print('-'*65)

comparison = [
    ('XLM-R-v1 (Baseline)',     XLMR_F1),
    ('PhoBERT-v2 (Classifier)', PHOBERT_F1),
    ('Gemma-4 4B (XAI Engine)', GEMMA_F1),
]
for name, f1 in comparison:
    avg = sum(f1.values()) / len(f1) if len(f1) > 0 else 0
    print(f"{name:<25} {f1.get('misinfo',0):>10.4f} {f1.get('stance',0):>10.4f} {f1.get('sentiment',0):>12.4f} {avg:>8.4f}")

print('='*65)

"""### (Optional) Bước 14: Quick Test — Phân tích mẫu thực"""

# [CELL 16] Test nhanh với 3 mẫu điển hình
test_samples = [
    ("Ko tiêm mũi nào hết. Cha mẹ thời nay bị doạ cho sợ hãi, chả có tác dụng gì còn gây hại.",
     "Tin giả | Phản đối | Tiêu cực"),
    ("Mình vừa tiêm xong mũi 2, bs bảo vx an toàn, không lo phản ứng phụ.",
     "Chính xác | Ủng hộ | Tích cực"),
    ("Bé nhà tôi tiêm 5 trong 1 xong bị sốt 38.5, có sao không ạ?",
     "Không liên quan | Không rõ | Tiêu cực"),
]

model.config.use_cache = True
print('🧪 QUICK TEST — 3 mẫu điển hình\n')

for i, (text, expected) in enumerate(test_samples):
    msgs = build_prompt(text)
    prompt_str = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
    forced_str = prompt_str + "Lý luận:\n"
    inputs = tokenizer(text=forced_str, return_tensors="pt").to("cuda")
    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=200, temperature=0.1, do_sample=True)
    generated = tokenizer.decode(out[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
    m, st, se, ok = parse_output(generated)

    label_str = f"{MISINFO_MAP.get(m,'?')} | {STANCE_MAP.get(st,'?')} | {SENTIMENT_MAP.get(se,'?')}"
    print(f'[{i+1}] {text[:70]}...')
    print(f'  Expected : {expected}')
    print(f'  Predicted: {label_str} (parse_ok={ok})')
    print(f'  Reasoning: {generated[:200]}...')
    print()