# -*- coding: utf-8 -*-
"""VaccineNLP · XLM-R-v1 Multitask Classifi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/inhlqunhphng/vaccinenlp-xlm-r-v1-multitask-classifi.df83c459-1485-4603-8277-39086d032f61.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260508/auto/storage/goog4_request%26X-Goog-Date%3D20260508T181541Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7b2237385645ecc757e060dfe00053a6f3ca1a75ccb0756034bcb76fb156e53a241144f2b06b0c787e1673519ec030da37ba12fb16b92944e743e92380a20fd56f1ecf9a757a2eee1a2827ab5fc0bbde16978a54ba16cadec772c7654d4f35c5694298f3d038194541b4e118e04bb3f2f67d7725f8a446a4068c30ae3f10c162d87ad33e5f97dd264c9d8fe5a492f5df1553379ca2138514d7597f4b696209a3e9710199ce8addcf3344e1f44fa233bf8563df77f22b87b1ab1e67b2f029f5c96c231faed7b6a63a350b69e8a52edba45f8ecc7fc1551d2c934c6842ab2678f5d99c4f3abc1e28ef904d1d7b475c233f2110a6d7318f1d5ba516de8b63a09fe8
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
inhlqunhphng_vaccinenlp_clean_data_path = kagglehub.dataset_download('inhlqunhphng/vaccinenlp-clean-data')

print('Data source import complete.')

"""# 💉 VaccineNLP · XLM-R-v1 Multitask Classifier
## Phát hiện Tin giả Vắc-xin & Phân tích Thái độ Cộng đồng (Tiếng Việt)

**Tác giả:** Kim Mạnh Hưng (2211090016) · Đinh Lê Quỳnh Phương (2211090031)  
**Người hướng dẫn:** TS. Trần Lâm Quân  
**Trường:** Đại học Y tế Công cộng (HUPH)  
**Môi trường:** Kaggle · GPU T4 x2  

---

### Tổng quan kiến trúc

Notebook này huấn luyện **Động cơ Phân loại** (Discriminator) trong kiến trúc **Dual-Student Hybrid** của dự án VaccineNLP.
Mô hình sử dụng **XLM-R** (`FacebookAI/xlm-roberta-base`) — pretrained encoder đa ngôn ngữ —
kết hợp với **Multi-task Learning** để dự đoán đồng thời 3 trục phân loại:

| Task | Nhãn | Lý do quan trọng |
|---|---|---|
| **Misinformation** | Không liên quan / Tin giả / Chính xác | Mục tiêu chính của đề tài |
| **Stance** | Ủng hộ / Phản đối / Trung lập / Không rõ | 4 nhãn — Fallback Bucket cho edge cases |
| **Sentiment** | Tiêu cực / Trung tính / Tích cực | Hỗ trợ phân tích thái độ cộng đồng |

### Các quyết định thiết kế then chốt

- **Weighted CrossEntropyLoss**: Bắt buộc do mất cân bằng nhãn nghiêm trọng. Nhãn *Tin giả* chỉ chiếm ~15% corpus.
- **Multi-task Learning (3 heads)**: Gradient từ 3 task cùng cập nhật encoder — regularization tự nhiên.
- **Early Stopping (patience=3)**: Tự động chọn checkpoint tốt nhất, ngăn overfitting trên Silver Labels.
- **Stance = 4 nhãn** (Hard Constraint): Nhãn *Không rõ* là Fallback Bucket — không được đổi thành 3.

> ✅ **Notebook tương thích với "Save & run all" của Kaggle** — không cần restart thủ công.

## ⚡ Quick Start — Cấu hình Trước Khi Chạy

> **Chỉ cần sửa 2 dòng dưới đây**, toàn bộ notebook sẽ chạy đúng.

### Bước 1 · Thêm Dataset vào Notebook
Trong Kaggle sidebar → **+ Add Data** → tìm `mnhhngkim/vaccinenlp-clean-data` → Add.

### Bước 2 · Bật GPU
Kaggle sidebar → **Session options** → Accelerator → **GPU T4 x2** → Save.

### Bước 3 · Chạy All
Menu **Run → Run All** (hoặc Shift+Enter từng cell).

---

### Cấu trúc file dữ liệu cần có
```
/kaggle/input/<dataset>/
    ├── 05_model_ready/
    │   └── train_v2_seg.jsonl      ← Training data (đã word-segment)
    └── 03_processed/
        └── benchmark_test_set.jsonl ← Gold Test Set (186 mẫu)
```

### Cấu trúc mỗi dòng JSONL
```json
{"text_segmented": "vắc xin Pfizer an_toàn cho trẻ_em",
 "standardized_ids": [2, 0, 2]}
```
*(standardized_ids = [misinfo_id, stance_id, sentiment_id])*

## 1. Cài đặt Môi trường

Kaggle đã pre-install `torch` và `transformers` với CUDA — **không upgrade** để tránh conflict.
Chỉ cần cài thêm `underthesea` cho word segmentation tiếng Việt.
"""

# [CELL 1] Kiểm tra môi trường & cài underthesea
import torch

# ✅ FIX: Kiểm tra GPU trước khi chạy bất cứ thứ gì
if not torch.cuda.is_available():
    raise RuntimeError(
        "❌ Không tìm thấy GPU!\n"
        "   → Kaggle sidebar → Session options → Accelerator → GPU T4 x2 → Save\n"
        "   → Sau đó chạy lại notebook"
    )

print(f"✅ PyTorch  : {torch.__version__}")
print(f"✅ CUDA     : {torch.version.cuda}")
print(f"✅ GPU      : {torch.cuda.get_device_name(0)}")
print(f"✅ VRAM     : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

import transformers
print(f"✅ Transformers: {transformers.__version__}")

# Cài underthesea (word segmentation tiếng Việt)
import subprocess
result = subprocess.run(
    ["pip", "install", "-q", "underthesea"],
    capture_output=True, text=True
)
if result.returncode == 0:
    print("✅ underthesea: OK")
else:
    print(f"⚠️  underthesea install warning: {result.stderr[-200:]}")

print("\n✅ Setup hoàn tất!")

"""## 2. Import Thư viện & Cấu hình GPU"""

# [CELL 2] Imports
import os, json, time, warnings
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModel, AutoTokenizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
from tqdm.auto import tqdm
import matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')

DEVICE   = torch.device("cuda")
gpu_name = torch.cuda.get_device_name(0)
vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"✅ Device : {DEVICE} | {gpu_name}")
print(f"✅ VRAM   : {vram_gb:.1f} GB")
print(f"✅ BF16   : {'supported' if torch.cuda.is_bf16_supported() else 'not supported (dùng FP32)'}")

"""## 3. Cấu hình Thực nghiệm (Hyperparameters)

Tất cả hyperparameter được tập trung tại một cell duy nhất để đảm bảo **reproducibility**.

**Lưu ý thiết kế:**
- `TASK_WEIGHTS = [0.5, 0.3, 0.2]`: Misinformation được ưu tiên cao nhất vì là mục tiêu chính của đề tài.
- `N_CLASSES['stance'] = 4`: **Hard constraint** — Nhãn thứ 4 (`Không rõ`) là *Fallback Bucket*. Không được đổi thành 3.
- `PATIENCE = 3`: Early stopping ngăn overfitting trên tập Silver Labels có nhiễu LLM (~2%).

"""

# [CELL 3] CẤU HÌNH TẬP TRUNG — Chỉ sửa tại đây

# ── Paths ──────────────────────────────────────────────────────────────────
MODEL_NAME = "FacebookAI/xlm-roberta-base"
TRAIN_PATH = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data/05_model_ready/train_v2_seg.jsonl"
TEST_PATH  = "/kaggle/input/datasets/inhlqunhphng/vaccinenlp-clean-data/03_processed/benchmark_test_set.jsonl"
SAVE_DIR   = "/kaggle/working/xlm-roberta-base"
os.makedirs(SAVE_DIR, exist_ok=True)

# ── Hyperparameters ─────────────────────────────────────────────────────────
MAX_LEN      = 256    # XLM-R max seq length
BATCH_SIZE   = 16     # T4 16GB với MAX_LEN=256
LR           = 2e-5   # Learning rate chuẩn cho BERT fine-tuning
EPOCHS       = 10     # Early stopping sẽ dừng sớm hơn
PATIENCE     = 3      # Số epoch chờ khi val_loss không cải thiện
SEED         = 42
TASK_WEIGHTS = [0.5, 0.3, 0.2]   # loss: misinfo / stance / sentiment

# ── Taxonomy (HARD CONSTRAINT: Stance có 4 nhãn) ───────────────────────────
N_CLASSES = {'misinfo': 3, 'stance': 4, 'sentiment': 3}
LABEL_NAMES = {
    'misinfo':   ['Không liên quan', 'Tin giả', 'Chính xác'],
    'stance':    ['Ủng hộ', 'Phản đối', 'Trung lập', 'Không rõ'],
    'sentiment': ['Tiêu cực', 'Trung tính', 'Tích cực'],
}
TASKS = list(N_CLASSES.keys())

# Set random seeds
torch.manual_seed(SEED)
np.random.seed(SEED)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
print(f"✅ Tokenizer loaded: {MODEL_NAME}")
print(f"   Vocab size: {tokenizer.vocab_size:,}")
print(f"   Max length: {MAX_LEN}")

"""## 4. Tải & Chuẩn bị Dữ liệu

### Nguồn dữ liệu
- **Train (90%)**: `train_v2_seg.jsonl` — Silver Labels từ Gemma-4 31B (Teacher Model), đã word-segment sẵn.
- **Test (Gold)**: `benchmark_test_set.jsonl` — **186 mẫu** đã qua Human-in-the-Loop validation.

### Chiến lược Split
```
train_v2_seg.jsonl (~1,670 mẫu)
    ├── 90% → Training Set  (~1,503 mẫu)
    └── 10% → Validation Set (~167 mẫu)  [stratify theo 'misinfo']

benchmark_test_set.jsonl (186 mẫu) → Gold Test Set [KHÔNG đụng vào khi train]
```

"""

# [CELL 4] Kiểm tra đường dẫn dữ liệu
print("Kiểm tra đường dẫn dữ liệu...")
missing = []
for label, path in [("TRAIN", TRAIN_PATH), ("TEST", TEST_PATH)]:
    exists = os.path.exists(path)
    size   = f"{os.path.getsize(path)/1024:.1f} KB" if exists else "N/A"
    status = "✅" if exists else "❌ KHÔNG TÌM THẤY"
    print(f"  {status} [{label}] {path}  ({size})")
    if not exists:
        missing.append(path)

if missing:
    # Liệt kê toàn bộ file có sẵn để debug
    print("\n📂 Files có sẵn trong /kaggle/input:")
    for root, dirs, files in os.walk('/kaggle/input'):
        for fn in files:
            if fn.endswith('.jsonl'):
                print(f"   {os.path.join(root, fn)}")
    raise FileNotFoundError(
        "\n❌ Không tìm thấy file dữ liệu — xem danh sách trên để chỉnh TRAIN_PATH / TEST_PATH"
    )

print("\n✅ Tất cả file đã sẵn sàng!")

# [CELL 5] Load JSONL & Stratified Split
from underthesea import word_tokenize

def load_jsonl(path):
    """Load JSONL — ưu tiên text_segmented, fallback word_tokenize."""
    data = []
    with open(path, 'r', encoding='utf-8') as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                print(f"  ⚠️  Dòng {line_no} lỗi JSON — bỏ qua")
                continue

            text = item.get('text_segmented') or word_tokenize(
                item.get('text_cleaned') or item.get('text', ''), format='text'
            )
            if not text or not text.strip():
                continue

            ids = item.get('standardized_ids', [0, 2, 1])
            while len(ids) < 3:
                ids.append(0)

            data.append({
                'text':      text.strip(),
                'misinfo':   int(ids[0]),
                'stance':    int(ids[1]),
                'sentiment': int(ids[2]),
            })
    return pd.DataFrame(data)

df_train_full = load_jsonl(TRAIN_PATH)
df_test       = load_jsonl(TEST_PATH)

# Stratified split theo 'misinfo' (lớp thiểu số: Tin giả ~15%)
df_train, df_val = train_test_split(
    df_train_full, test_size=0.1, random_state=SEED,
    stratify=df_train_full['misinfo']
)
df_train = df_train.reset_index(drop=True)
df_val   = df_val.reset_index(drop=True)

print(f"✅ Dataset loaded:")
print(f"   Train: {len(df_train):,} | Val: {len(df_val):,} | Test (Gold): {len(df_test):,}")
print()
for t in TASKS:
    dist  = dict(sorted(df_train[t].value_counts().items()))
    named = {LABEL_NAMES[t][k]: v for k, v in dist.items() if k < len(LABEL_NAMES[t])}
    print(f"   {t:10s}: {named}")

"""## 5. PyTorch Dataset & DataLoader

`VaccineDataset` tokenize với XLM-R tokenizer và đóng gói labels 3 task vào một batch.
Padding về `MAX_LEN=256` để đảm bảo batch hợp lệ trên GPU.

"""

# [CELL 6] VaccineDataset + DataLoaders
class VaccineDataset(Dataset):
    """PyTorch Dataset cho VaccineNLP Multi-task Classification."""

    def __init__(self, df: pd.DataFrame, tokenizer, max_len: int = 256):
        self.texts     = df['text'].tolist()
        self.labels    = {t: df[t].values for t in TASKS}
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding='max_length',
            max_length=self.max_len,
            return_tensors='pt'
        )
        out = {k: v.squeeze(0) for k, v in enc.items()}
        for t in TASKS:
            out[t] = torch.tensor(int(self.labels[t][idx]), dtype=torch.long)
        return out


train_loader = DataLoader(VaccineDataset(df_train, tokenizer, MAX_LEN),
                          batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(VaccineDataset(df_val,   tokenizer, MAX_LEN),
                          batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(VaccineDataset(df_test,  tokenizer, MAX_LEN),
                          batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f"✅ DataLoaders ready:")
print(f"   Train batches : {len(train_loader)}")
print(f"   Val batches   : {len(val_loader)}")
print(f"   Test batches  : {len(test_loader)}")

"""## 6. Kiến trúc Mô hình: XLM-R Multitask Classifier

### Thiết kế Multi-task Head
Ba classification head độc lập chia sẻ cùng một **XLM-R encoder**.

### Weighted CrossEntropyLoss — Lý do bắt buộc
- *Tin giả* chỉ ~15% → Model naive sẽ bias về *Chính xác*.
- `class_weight='balanced'` tính trọng số tỷ lệ nghịch với tần suất nhãn.
- **Hard Constraint** — không được thay bằng standard CrossEntropyLoss.

"""

# [CELL 7] MultitaskClassifier + Loss + Optimizer
class MultitaskClassifier(nn.Module):
    """
    XLM-R + 3 classification heads (Multi-task Learning).
    Shared encoder — independent heads để tối ưu từng task.
    """
    def __init__(self, model_name: str, n_classes: dict):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        hidden_size  = self.encoder.config.hidden_size   # 768
        self.dropout = nn.Dropout(0.1)
        self.heads   = nn.ModuleDict({
            task: nn.Linear(hidden_size, n)
            for task, n in n_classes.items()
        })

    def forward(self, input_ids, attention_mask, **kwargs):
        pooled = self.encoder(
            input_ids=input_ids, attention_mask=attention_mask
        ).pooler_output
        pooled = self.dropout(pooled)
        return {task: head(pooled) for task, head in self.heads.items()}


model        = MultitaskClassifier(MODEL_NAME, N_CLASSES).to(DEVICE)
total_params = sum(p.numel() for p in model.parameters())
trainable    = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✅ Model: {total_params/1e6:.1f}M params ({trainable/1e6:.1f}M trainable)")

# ── Weighted CrossEntropyLoss (Hard Constraint) ───────────────────────────
loss_fns = {}
for task, n in N_CLASSES.items():
    vals    = df_train[task].values
    present = np.array(sorted(set(vals)))
    weights = np.ones(n, dtype=np.float32)
    cw = compute_class_weight('balanced', classes=present, y=vals)
    for i, c in enumerate(present):
        weights[c] = cw[i]
    loss_fns[task] = nn.CrossEntropyLoss(weight=torch.tensor(weights).to(DEVICE))
    print(f"   Loss [{task:10s}]: weights = {np.round(weights, 3).tolist()}")

# ── Optimizer & Scheduler ─────────────────────────────────────────────────
total_steps = len(train_loader) * EPOCHS
optimizer   = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=0.01)
scheduler   = torch.optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=LR, total_steps=total_steps
)
print(f"\n✅ Optimizer: AdamW (lr={LR}) | Scheduler: OneCycleLR ({total_steps} steps)")

"""## 7. Vòng Lặp Huấn luyện (Training Loop)

`run_epoch` dùng chung cho train và eval.
**Early Stopping** dựa trên `val_loss` — tự động chọn checkpoint tốt nhất.

**Loss tổng hợp** = `0.5 × L_misinfo + 0.3 × L_stance + 0.2 × L_sentiment`

"""

# [CELL 8] run_epoch + Training Loop + Early Stopping
def run_epoch(model, loader, train: bool = True):
    """Chạy 1 epoch. Trả về (avg_loss, f1_dict, preds_dict, labels_dict)."""
    model.train() if train else model.eval()
    total_loss = 0.0
    all_preds  = {t: [] for t in TASKS}
    all_labels = {t: [] for t in TASKS}

    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for batch in (tqdm(loader, desc='Train', leave=False) if train else loader):
            ids  = batch['input_ids'].to(DEVICE)
            mask = batch['attention_mask'].to(DEVICE)
            logits = model(ids, mask)

            loss = sum(
                TASK_WEIGHTS[i] * loss_fns[t](logits[t], batch[t].to(DEVICE))
                for i, t in enumerate(TASKS)
            )

            if train:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()

            total_loss += loss.item()
            for t in TASKS:
                all_preds[t].extend(logits[t].argmax(1).cpu().tolist())
                all_labels[t].extend(batch[t].tolist())

    avg_loss = total_loss / len(loader)
    f1s = {
        t: f1_score(all_labels[t], all_preds[t], average='macro', zero_division=0)
        for t in TASKS
    }
    return avg_loss, f1s, all_preds, all_labels


# ── Training Loop ─────────────────────────────────────────────────────────
history = {k: [] for k in ['train_loss', 'val_loss'] + [f'f1_{t}' for t in TASKS]}
best_val_loss = float('inf')
wait  = 0
t0    = time.time()

print(f"{'Epoch':>5} {'TrainLoss':>10} {'ValLoss':>10} {'Misinfo':>8} {'Stance':>8} {'Sentiment':>10}  Note")
print("-" * 75)

for ep in range(1, EPOCHS + 1):
    tl, _,   _, _  = run_epoch(model, train_loader, train=True)
    vl, vf1, _, _  = run_epoch(model, val_loader,   train=False)

    history['train_loss'].append(tl)
    history['val_loss'].append(vl)
    for t in TASKS:
        history[f'f1_{t}'].append(vf1[t])

    note = ''
    if vl < best_val_loss:
        best_val_loss = vl
        wait = 0
        torch.save(model.state_dict(), f"{SAVE_DIR}/best_model.pt")
        note = '✅ BEST'
    else:
        wait += 1
        note = f'wait {wait}/{PATIENCE}'

    print(f"{ep:5d} {tl:10.4f} {vl:10.4f} "
          f"{vf1['misinfo']:8.4f} {vf1['stance']:8.4f} {vf1['sentiment']:10.4f}  {note}")

    if wait >= PATIENCE:
        print("⏹  Early stopping triggered.")
        break

train_secs = int(time.time() - t0)
print(f"\n✅ Training hoàn tất: {train_secs}s ({train_secs//60} phút {train_secs%60}s)")
print(f"   Best Val Loss  : {best_val_loss:.4f}")
print(f"   Checkpoint     : {SAVE_DIR}/best_model.pt")

"""## 8. Trực quan hóa Quá trình Huấn luyện

Loss curves và Validation F1 theo epoch giúp chẩn đoán overfitting / underfitting.
Đường xanh lá = checkpoint tốt nhất (Best epoch).

"""

# [CELL 9] Training Curves
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('XLM-R-v1 · Training Curves', fontsize=14, fontweight='bold')

# Loss curves
ax = axes[0]
ax.plot(history['train_loss'], 'b-o', label='Train Loss', markersize=4)
ax.plot(history['val_loss'],   'r-s', label='Val Loss',   markersize=4)
best_ep = int(np.argmin(history['val_loss']))
ax.axvline(best_ep, color='green', ls='--', alpha=0.7, label=f'Best Epoch ({best_ep+1})')
ax.set(xlabel='Epoch', ylabel='Loss', title='Loss Curves')
ax.legend(); ax.grid(True, alpha=0.3)

# F1 curves
ax = axes[1]
colors = {'misinfo': '#e74c3c', 'stance': '#3498db', 'sentiment': '#2ecc71'}
for t, c in colors.items():
    ax.plot(history[f'f1_{t}'], '-o', color=c, label=t.capitalize(), markersize=4)
ax.set(xlabel='Epoch', ylabel='Macro F1', title='Validation F1 (mỗi task)')
ax.legend(); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/training_curves.png", dpi=150, bbox_inches='tight')
plt.show()
print(f"✅ Saved: {SAVE_DIR}/training_curves.png")

"""## 9. Đánh giá trên Gold Test Set (Benchmark)

> ⚠️ **Tập này hoàn toàn tách biệt khỏi quá trình huấn luyện.**
> 186 mẫu đã qua Human-in-the-Loop validation — đây là Ground Truth duy nhất để so sánh mô hình.

### Kết quả tham chiếu (từ Báo cáo Kỹ thuật)

| Task | Macro F1 |
|---|---|
| Misinformation | **0.4547** |
| Stance | **0.6608** |
| Sentiment | **0.7325** |

*Misinfo F1 thấp do nhãn `Không liên quan` có support=0 trong test set — kéo macro trung bình xuống. Đây là hiện tượng bình thường với zero-support classes.*

"""

# [CELL 10] Load best checkpoint & đánh giá Gold Test Set
best_ckpt = f"{SAVE_DIR}/best_model.pt"
if not os.path.exists(best_ckpt):
    raise FileNotFoundError(
        f"❌ Không tìm thấy checkpoint: {best_ckpt}\n"
        "   → Training Loop (Cell 8) phải chạy thành công trước."
    )

model.load_state_dict(torch.load(best_ckpt, map_location=DEVICE))
print(f"✅ Loaded best checkpoint: {best_ckpt}")

_, test_f1s, test_preds, test_labels = run_epoch(model, test_loader, train=False)

print("\n" + "=" * 65)
print("BENCHMARK — GOLD TEST SET (186 mẫu, Human-validated)")
print("=" * 65)

for t in TASKS:
    present = sorted(set(test_labels[t]))
    tnames  = [LABEL_NAMES[t][i] for i in present if i < len(LABEL_NAMES[t])]
    print(f"\n{'─'*60}")
    print(f"  {t.upper()}  (Macro F1 = {test_f1s[t]:.4f})")
    print(f"{'─'*60}")
    print(classification_report(
        test_labels[t], test_preds[t],
        labels=present, target_names=tnames, zero_division=0
    ))

print("=" * 65)
print("SUMMARY")
print("=" * 65)
for t in TASKS:
    print(f"  {t:12s}: Macro F1 = {test_f1s[t]:.4f}")

"""## 10. Xuất Kết quả — Định dạng chuẩn dự án

File `xlmr_v1_results.json` xuất theo **đúng schema** của `experiments/results/` trong repo VaccineNLP:

```json
{
  "model": "xlmr-base",
  "timestamp": "...",
  "misinfo":   { "macro_f1": ..., "per_class": [...], "support": [...] },
  "stance":    { "macro_f1": ..., "per_class": [...], "support": [...] },
  "sentiment": { "macro_f1": ..., "per_class": [...], "support": [...] },
  "val_loss_best": ...,
  "training_seconds": ...
}
```

Schema này **đồng nhất 100%** với `xlmr_v1_results.json` và `phobert_v2_results.json` trong repo —
notebook Gemma sẽ đọc được trực tiếp mà không cần chỉnh sửa.

"""

# [CELL 11] Export kết quả — schema chuẩn experiments/results/
# Đồng nhất với xlmr_v1_results.json và phobert_v2_results.json trong repo

import datetime

def per_class_f1_support(y_true, y_pred, n_classes):
    """Tính F1 và support cho từng class. Index 0..n_classes-1."""
    f1s, sups = [], []
    for c in range(n_classes):
        yt = [1 if y == c else 0 for y in y_true]
        yp = [1 if y == c else 0 for y in y_pred]
        f1s.append(round(f1_score(yt, yp, zero_division=0), 4))
        sups.append(int(sum(yt)))
    return f1s, sups

# ── Build kết quả theo đúng schema dự án ─────────────────────────────────
results = {
    "model":            "xlmr-base",
    "timestamp":        datetime.datetime.now().isoformat(),
    "val_loss_best":    round(best_val_loss, 4),
    "training_seconds": train_secs,
}

for t in TASKS:
    n  = N_CLASSES[t]
    f1s, sups = per_class_f1_support(test_labels[t], test_preds[t], n)
    results[t] = {
        "macro_f1":  round(test_f1s[t], 4),
        "per_class": f1s,
        "support":   sups,
    }

# ── Lưu file ─────────────────────────────────────────────────────────────
OUT_PATH = f"{SAVE_DIR}/xlmr_v1_results.json"
with open(OUT_PATH, 'w', encoding='utf-8') as f:
    json.dump(results, f, indent=2, ensure_ascii=False)

print(f"✅ Saved: {OUT_PATH}")
print()
print(json.dumps(results, indent=2, ensure_ascii=False))
print()

# ── Kiểm tra nhanh schema (guard) ────────────────────────────────────────
required_keys = {"model", "timestamp", "val_loss_best", "training_seconds",
                 "misinfo", "stance", "sentiment"}
task_keys     = {"macro_f1", "per_class", "support"}
assert required_keys <= set(results.keys()), "❌ Thiếu top-level key!"
for t in TASKS:
    assert task_keys <= set(results[t].keys()), f"❌ Task '{t}' thiếu key!"
    assert len(results[t]["per_class"]) == N_CLASSES[t], (
        f"❌ per_class length sai cho {t}: "
        f"expected {N_CLASSES[t]}, got {len(results[t]['per_class'])}"
    )
    assert len(results[t]["support"]) == N_CLASSES[t], (
        f"❌ support length sai cho {t}: "
        f"expected {N_CLASSES[t]}, got {len(results[t]['support'])}"
    )
print("✅ Schema validation OK — file sẵn sàng dùng trong notebook Gemma")

"""## 11. Confusion Matrix — Phân tích Lỗi Trực quan

Confusion matrix trên Gold Test Set giúp xác định:
- Nhãn nào model hay nhầm lẫn nhất?
- **False Negative quan trọng**: Model bỏ sót *Tin giả* → phân loại thành *Chính xác*?

"""

# [CELL 12] Confusion Matrix — 3 tasks
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('XLM-R-v1 · Confusion Matrix (Gold Test Set, n=186)',
             fontsize=14, fontweight='bold')

for i, t in enumerate(TASKS):
    present = sorted(set(test_labels[t]) | set(test_preds[t]))
    cm      = confusion_matrix(test_labels[t], test_preds[t], labels=present)
    names   = [LABEL_NAMES[t][j] for j in present if j < len(LABEL_NAMES[t])]
    sns.heatmap(
        cm, annot=True, fmt='d', cmap='Blues',
        ax=axes[i], xticklabels=names, yticklabels=names
    )
    axes[i].set_title(
        f'{t.capitalize()}\nMacro F1 = {test_f1s[t]:.4f}',
        fontweight='bold'
    )
    axes[i].set_ylabel('True Label')
    axes[i].set_xlabel('Predicted Label')
    axes[i].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/confusion_matrices.png", dpi=150, bbox_inches='tight')
plt.show()
print(f"✅ Saved: {SAVE_DIR}/confusion_matrices.png")

"""## 12. So sánh 3 Mô hình — Đọc từ File JSON Chuẩn"""

# [CELL 13] So sánh 3 mô hình — đọc từ file JSON chuẩn dự án
# Notebook Gemma dùng logic tương tự để vẽ bảng này

import os

# ── Load kết quả từ file JSON ─────────────────────────────────────────────
# XLM-R: vừa tạo ở Cell 11
xlmr_path = f"{SAVE_DIR}/xlmr_v1_results.json"
with open(xlmr_path) as f:
    xlmr_res = json.load(f)

# PhoBERT-v2 & Gemma: giá trị đã xác nhận từ Báo cáo Kỹ thuật (hardcoded fallback)
PHOBERT_RES = {
    "model": "phobert-v2",
    "misinfo":   {"macro_f1": 0.4547, "per_class": [0.0,    0.4667, 0.8974],       "support": [0,  28, 158]},
    "stance":    {"macro_f1": 0.6608, "per_class": [0.6095, 0.6139, 0.759],         "support": [54, 48, 84]},
    "sentiment": {"macro_f1": 0.7325, "per_class": [0.7206, 0.7947, 0.6824],        "support": [71, 75, 40]},
}
GEMMA_RES = {
    "model": "gemma-4-4b-xai",
    "misinfo":   {"macro_f1": 0.44,   "per_class": [0.0,  0.51, 0.8],              "support": [0,  28, 158]},
    "stance":    {"macro_f1": 0.62,   "per_class": [0.58, 0.56, 0.71, 0.0],        "support": [54, 48, 84, 0]},
    "sentiment": {"macro_f1": 0.66,   "per_class": [0.68, 0.67, 0.62],             "support": [71, 75, 40]},
}

# ── Bảng Macro F1 tổng hợp ────────────────────────────────────────────────
all_models = [
    ("XLM-R-v1 (này)",          xlmr_res),
    ("PhoBERT-v2 (Classifier)", PHOBERT_RES),
    ("Gemma-4 4B (XAI Engine)", GEMMA_RES),
]

print("=" * 70)
print("BENCHMARK COMPARISON — Macro F1 (Gold Test Set, n=186)")
print("=" * 70)
print(f"{'Model':<28} {'Misinfo':>9} {'Stance':>9} {'Sentiment':>11} {'Avg':>8}")
print("-" * 70)
for name, res in all_models:
    m  = res["misinfo"]["macro_f1"]
    st = res["stance"]["macro_f1"]
    se = res["sentiment"]["macro_f1"]
    avg = round((m + st + se) / 3, 4)
    print(f"{name:<28} {m:>9.4f} {st:>9.4f} {se:>11.4f} {avg:>8.4f}")
print("=" * 70)

# ── Per-class breakdown ───────────────────────────────────────────────────
print()
print("PER-CLASS F1 BREAKDOWN")
print("=" * 70)

for t in TASKS:
    print(f"\n  {t.upper()}")
    print(f"  {'Label':<20} {'XLM-R':>8} {'PhoBERT':>9} {'Gemma':>8}")
    print(f"  {'-'*48}")
    n = max(len(xlmr_res[t]["per_class"]),
            len(PHOBERT_RES[t]["per_class"]),
            len(GEMMA_RES[t]["per_class"]))
    for c in range(n):
        label = LABEL_NAMES[t][c] if c < len(LABEL_NAMES[t]) else f"Class {c}"
        xlmr_f1   = xlmr_res[t]["per_class"][c]   if c < len(xlmr_res[t]["per_class"])   else "-"
        phobert_f1 = PHOBERT_RES[t]["per_class"][c] if c < len(PHOBERT_RES[t]["per_class"]) else "-"
        gemma_f1   = GEMMA_RES[t]["per_class"][c]   if c < len(GEMMA_RES[t]["per_class"])   else "-"
        sup = xlmr_res[t]["support"][c] if c < len(xlmr_res[t]["support"]) else 0
        xlmr_s   = f"{xlmr_f1:.4f}"   if isinstance(xlmr_f1, float)   else xlmr_f1
        phob_s   = f"{phobert_f1:.4f}" if isinstance(phobert_f1, float) else phobert_f1
        gem_s    = f"{gemma_f1:.4f}"   if isinstance(gemma_f1, float)   else gemma_f1
        print(f"  {label:<20} {xlmr_s:>8} {phob_s:>9} {gem_s:>8}  (n={sup})")

"""## 13. (Tùy chọn) Upload lên Hugging Face Hub

Model đã được public tại: [quynhphuong1209/xlmr-multitask](https://huggingface.co/quynhphuong1209/xlmr-multitask)

"""

# [CELL 14] Upload HuggingFace Hub (optional — wrap try/except, không crash nếu lỗi)
try:
    from huggingface_hub import login, HfApi
    from kaggle_secrets import UserSecretsClient
    VaccineNLP_TOKEN = UserSecretsClient().get_secret("VaccineNLP")
    if HF_TOKEN:
        login(token=VaccineNLP_TOKEN, add_to_git_credential=False)
        api = HfApi()
        api.upload_folder(
            folder_path = SAVE_DIR,
            repo_id     = "quynhphuong1209/xlmr-multitask",
            repo_type   = "model",
        )
        print("✅ Uploaded to HuggingFace: quynhphuong1209/xlmr-multitask")
    else:
        print("⚠️  VaccineNLP rỗng — bỏ qua upload")
except Exception as e:
    print(f"⚠️  HF upload thất bại (không ảnh hưởng kết quả): {e}")

# ── Tổng kết ──────────────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("✅ NOTEBOOK HOÀN TẤT")
print("=" * 55)
print(f"   Model weights    : {SAVE_DIR}/best_model.pt")
print(f"   Results JSON     : {SAVE_DIR}/xlmr_v1_results.json")
print(f"   Training curves  : {SAVE_DIR}/training_curves.png")
print(f"   Confusion matrix : {SAVE_DIR}/confusion_matrices.png")
print()
print("📋 Dùng results JSON trong notebook Gemma:")
print(f'   with open("{SAVE_DIR}/xlmr_v1_results.json") as f:')
print(f'       xlmr_res = json.load(f)')