# =============================================================
# VaccineNLP — Streamlit Secrets Configuration
# =============================================================

# Nhập Hugging Face Token của bạn vào đây để tải mô hình nhanh nhất
HF_TOKEN = "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"
VaccineNLP_TOKEN = "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"
